// Generated from the translators' JSON (en + 18) by scratchpad i18n/merge.py. Do not edit by hand.
export const STRINGS = {
 "en": {
  "page_title": "Pythoneer — One Night",
  "get_app": "Get the app",
  "h1": "One night. Night 4.",
  "rules_html": "A Py lands and raises a tower. The swarm comes down both sides. <b>Keep every one of them off the torch.</b> Stomp them, or let your two friends on the tower shoot and bubble them. When the Py comes out, crack its shell twice, then touch it.",
  "night_name": "Night 4 · Vine Gauntlet",
  "lose_rule": "Lose if anything reaches the torch, or your three hearts run out.",
  "guest_soon": "After {n} losses a guest joins the tower.",
  "guest_count": "Lost {k} of {n} — after {n} losses a guest joins the tower.",
  "guest_here": "A guest Shooter (power 200) joins you on the first floor tonight.",
  "start": "Start the night",
  "swarm": "Swarm {n}",
  "py_in": "Py: comes out in {n}",
  "py_shell": "Py: shell {n}",
  "py_down": "Py: down {n}s",
  "say_out": "The Py is out — crack its shell",
  "say_broke": "The shell broke — hit it once more",
  "say_touch": "Touch the Py to seal it",
  "say_up": "The Py got back up — one shell layer",
  "sealed": "Sealed!",
  "sealed_line": "Vines is on your shelf · {n}/38. {s}s · the tower took {t}, you took {h}.",
  "torch_out": "The torch went out",
  "out_of_hearts": "Out of hearts",
  "lost_line": "{s}s · {e} reached the ground. {guest}",
  "try_again": "Try again",
  "your_house": "Your house",
  "move_left": "Move left",
  "move_right": "Move right",
  "jump": "JUMP",
  "keys_line": "← → / A D  Move · Space ↑ W  Jump · Tap the downed Py · Esc  Pause",
  "house_lede": "Every Py you bring home stands on the shelf. The ones who walk the floor are drawn in Spriteer.",
  "py_counts": "Pys {a}/{b} · Pets {c}/{d} · Fish {e}/{f}",
  "from_sp": "{n} from Spriteer",
  "none_from_sp": "No one from Spriteer yet",
  "door_py": "The floor is empty until someone moves in. Fill four dots at spriteer.com — your house goes with you.",
  "visit": "Visit",
  "all_nights": "Play all 38 nights in the app",
  "privacy": "Privacy"
 },
 "ar": {
  "page_title": "Pythoneer — ليلة واحدة",
  "get_app": "احصل على التطبيق",
  "h1": "ليلة واحدة. الليلة 4.",
  "rules_html": "يهبط باي ويرفع برجًا. ينزل السرب من الجانبين. <b>لا تدع أيًّا منهم يصل إلى الشعلة.</b> اقفز عليهم، أو دع صديقيك على البرج يطلقان عليهم ويحبسانهم في الفقاعات. عندما يخرج الباي، اكسر قوقعته مرتين، ثم المسه.",
  "night_name": "الليلة 4 · Vine Gauntlet",
  "lose_rule": "تخسر إذا وصل أي شيء إلى الشعلة، أو نفدت قلوبك الثلاثة.",
  "guest_soon": "بعد {n} خسارات ينضم ضيف إلى البرج.",
  "guest_count": "خسرت {k} من {n} — بعد {n} خسارات ينضم ضيف إلى البرج.",
  "guest_here": "ينضم إليك الليلة رامٍ ضيف (القوة 200) في الطابق الأول.",
  "start": "ابدأ الليلة",
  "swarm": "السرب {n}",
  "py_in": "باي: يخرج بعد {n}",
  "py_shell": "باي: القوقعة {n}",
  "py_down": "باي: ساقط {n} ث",
  "say_out": "خرج الباي — اكسر قوقعته",
  "say_broke": "انكسرت القوقعة — اضربه مرة أخرى",
  "say_touch": "المس الباي لختمه",
  "say_up": "نهض الباي من جديد — طبقة قوقعة واحدة",
  "sealed": "تم الختم!",
  "sealed_line": "Vines على رفّك · {n}/38. {s} ث · البرج أسقط {t}، وأنت {h}.",
  "torch_out": "انطفأت الشعلة",
  "out_of_hearts": "نفدت القلوب",
  "lost_line": "{s} ث · وصل {e} إلى الأرض. {guest}",
  "try_again": "حاول مجددًا",
  "your_house": "منزلك",
  "move_left": "تحرك يسارًا",
  "move_right": "تحرك يمينًا",
  "jump": "قفز",
  "keys_line": "← → / A D  تحرك · Space ↑ W  قفز · المس الباي الساقط · Esc  إيقاف مؤقت",
  "house_lede": "كل باي تعيده إلى المنزل يقف على الرف. أما من يمشون على الأرض فيُرسمون في Spriteer.",
  "py_counts": "باي {a}/{b} · حيوانات أليفة {c}/{d} · أسماك {e}/{f}",
  "from_sp": "{n} من Spriteer",
  "none_from_sp": "لا أحد من Spriteer بعد",
  "door_py": "الأرضية فارغة حتى ينتقل أحد إليها. املأ أربع نقاط على spriteer.com — منزلك يرافقك.",
  "visit": "زيارة",
  "all_nights": "العب الليالي الـ 38 كلها في التطبيق",
  "privacy": "الخصوصية"
 },
 "de": {
  "page_title": "Pythoneer — Eine Nacht",
  "get_app": "App laden",
  "h1": "Eine Nacht. Nacht 4.",
  "rules_html": "Ein Py landet und baut einen Turm. Der Schwarm kommt auf beiden Seiten herunter. <b>Lass keinen von ihnen an die Fackel.</b> Spring auf sie drauf, oder lass deine zwei Freunde auf dem Turm schießen und sie in Blasen packen. Wenn der Py herauskommt, knack zweimal seine Schale und berühr ihn dann.",
  "night_name": "Nacht 4 · Vine Gauntlet",
  "lose_rule": "Du verlierst, wenn etwas die Fackel erreicht oder deine drei Herzen weg sind.",
  "guest_soon": "Nach {n} Niederlagen kommt ein Gast auf den Turm.",
  "guest_count": "{k} von {n} verloren — nach {n} Niederlagen kommt ein Gast auf den Turm.",
  "guest_here": "Heute Nacht hilft dir ein Gast-Schütze (Stärke 200) im ersten Stock.",
  "start": "Nacht starten",
  "swarm": "Schwarm {n}",
  "py_in": "Py: kommt in {n}",
  "py_shell": "Py: Schale {n}",
  "py_down": "Py: am Boden {n} s",
  "say_out": "Der Py ist draußen — knack seine Schale",
  "say_broke": "Die Schale ist zerbrochen — noch ein Treffer",
  "say_touch": "Berühr den Py, um ihn zu versiegeln",
  "say_up": "Der Py ist wieder auf — eine Schalenschicht",
  "sealed": "Versiegelt!",
  "sealed_line": "Vines steht in deinem Regal · {n}/38. {s} s · der Turm erledigte {t}, du {h}.",
  "torch_out": "Die Fackel ist aus",
  "out_of_hearts": "Keine Herzen mehr",
  "lost_line": "{s} s · {e} erreichten den Boden. {guest}",
  "try_again": "Nochmal",
  "your_house": "Dein Haus",
  "move_left": "Nach links",
  "move_right": "Nach rechts",
  "jump": "SPRUNG",
  "keys_line": "← → / A D  Laufen · Space ↑ W  Springen · Liegenden Py antippen · Esc  Pause",
  "house_lede": "Jeder Py, den du heimbringst, steht im Regal. Wer über den Boden läuft, wird in Spriteer gezeichnet.",
  "py_counts": "Pys {a}/{b} · Haustiere {c}/{d} · Fische {e}/{f}",
  "from_sp": "{n} aus Spriteer",
  "none_from_sp": "Noch niemand aus Spriteer",
  "door_py": "Der Boden bleibt leer, bis jemand einzieht. Füll vier Punkte auf spriteer.com — dein Haus kommt mit dir.",
  "visit": "Besuchen",
  "all_nights": "Alle 38 Nächte in der App spielen",
  "privacy": "Datenschutz"
 },
 "es": {
  "page_title": "Pythoneer — Una noche",
  "get_app": "Descargar la app",
  "h1": "Una noche. Noche 4.",
  "rules_html": "Un Py aterriza y levanta una torre. El enjambre baja por los dos lados. <b>Que ninguno llegue a la antorcha.</b> Písalos, o deja que tus dos amigos de la torre les disparen y los atrapen en burbujas. Cuando salga el Py, rómpele el caparazón dos veces y luego tócalo.",
  "night_name": "Noche 4 · Vine Gauntlet",
  "lose_rule": "Pierdes si algo llega a la antorcha o se acaban tus tres corazones.",
  "guest_soon": "Tras {n} derrotas, un invitado se une a la torre.",
  "guest_count": "Perdiste {k} de {n} — tras {n} derrotas, un invitado se une a la torre.",
  "guest_here": "Esta noche un Tirador invitado (poder 200) te acompaña en el primer piso.",
  "start": "Empezar la noche",
  "swarm": "Enjambre {n}",
  "py_in": "Py: sale en {n}",
  "py_shell": "Py: caparazón {n}",
  "py_down": "Py: caído {n} s",
  "say_out": "El Py salió — rómpele el caparazón",
  "say_broke": "El caparazón se rompió — golpéalo una vez más",
  "say_touch": "Toca al Py para sellarlo",
  "say_up": "El Py se levantó — una capa de caparazón",
  "sealed": "¡Sellado!",
  "sealed_line": "Vines está en tu estante · {n}/38. {s} s · la torre se encargó de {t}, tú de {h}.",
  "torch_out": "La antorcha se apagó",
  "out_of_hearts": "Sin corazones",
  "lost_line": "{s} s · {e} llegaron al suelo. {guest}",
  "try_again": "Reintentar",
  "your_house": "Tu casa",
  "move_left": "Mover a la izquierda",
  "move_right": "Mover a la derecha",
  "jump": "SALTAR",
  "keys_line": "← → / A D  Mover · Space ↑ W  Saltar · Toca al Py caído · Esc  Pausa",
  "house_lede": "Cada Py que traes a casa está en el estante. Los que caminan por el suelo se dibujan en Spriteer.",
  "py_counts": "Pys {a}/{b} · Mascotas {c}/{d} · Peces {e}/{f}",
  "from_sp": "{n} de Spriteer",
  "none_from_sp": "Aún nadie de Spriteer",
  "door_py": "El suelo está vacío hasta que alguien se mude. Rellena cuatro puntos en spriteer.com — tu casa va contigo.",
  "visit": "Visitar",
  "all_nights": "Juega las 38 noches en la app",
  "privacy": "Privacidad"
 },
 "fr": {
  "page_title": "Pythoneer — Une nuit",
  "get_app": "Obtenir l'app",
  "h1": "Une nuit. Nuit 4.",
  "rules_html": "Un Py atterrit et dresse une tour. L'essaim descend des deux côtés. <b>Ne laisse aucun d'eux atteindre la torche.</b> Saute-leur dessus, ou laisse tes deux amis sur la tour tirer et les enfermer dans des bulles. Quand le Py sort, brise sa carapace deux fois, puis touche-le.",
  "night_name": "Nuit 4 · Vine Gauntlet",
  "lose_rule": "Perdu si quelque chose atteint la torche ou si tes trois cœurs s'épuisent.",
  "guest_soon": "Après {n} défaites, un invité rejoint la tour.",
  "guest_count": "{k} défaites sur {n} — après {n} défaites, un invité rejoint la tour.",
  "guest_here": "Un Tireur invité (puissance 200) te rejoint au premier étage cette nuit.",
  "start": "Commencer la nuit",
  "swarm": "Essaim {n}",
  "py_in": "Py : sort dans {n}",
  "py_shell": "Py : carapace {n}",
  "py_down": "Py : à terre {n} s",
  "say_out": "Le Py est sorti — brise sa carapace",
  "say_broke": "La carapace est brisée — encore un coup",
  "say_touch": "Touche le Py pour le sceller",
  "say_up": "Le Py s'est relevé — une couche de carapace",
  "sealed": "Scellé !",
  "sealed_line": "Vines est sur ton étagère · {n}/38. {s} s · la tour en a eu {t}, toi {h}.",
  "torch_out": "La torche s'est éteinte",
  "out_of_hearts": "Plus de cœurs",
  "lost_line": "{s} s · {e} ont touché le sol. {guest}",
  "try_again": "Réessayer",
  "your_house": "Ta maison",
  "move_left": "Aller à gauche",
  "move_right": "Aller à droite",
  "jump": "SAUT",
  "keys_line": "← → / A D  Bouger · Space ↑ W  Sauter · Touche le Py à terre · Esc  Pause",
  "house_lede": "Chaque Py que tu ramènes se tient sur l'étagère. Ceux qui marchent au sol sont dessinés dans Spriteer.",
  "py_counts": "Pys {a}/{b} · Animaux {c}/{d} · Poissons {e}/{f}",
  "from_sp": "{n} de Spriteer",
  "none_from_sp": "Personne de Spriteer pour l'instant",
  "door_py": "Le sol reste vide jusqu'à ce que quelqu'un emménage. Remplis quatre points sur spriteer.com — ta maison te suit.",
  "visit": "Visiter",
  "all_nights": "Joue les 38 nuits dans l'app",
  "privacy": "Confidentialité"
 },
 "hi": {
  "page_title": "Pythoneer — एक रात",
  "get_app": "ऐप लो",
  "h1": "एक रात। रात 4।",
  "rules_html": "एक पाई उतरता है और मीनार खड़ी करता है। झुंड दोनों तरफ़ से नीचे आता है। <b>उनमें से किसी को भी मशाल तक मत पहुँचने दो।</b> उन पर कूदो, या मीनार पर बैठे अपने दो दोस्तों को उन पर गोली चलाने और उन्हें बुलबुलों में बंद करने दो। जब पाई बाहर आए, उसका खोल दो बार तोड़ो, फिर उसे छुओ।",
  "night_name": "रात 4 · Vine Gauntlet",
  "lose_rule": "अगर कुछ भी मशाल तक पहुँच गया, या तुम्हारे तीनों दिल खत्म हो गए, तो हार।",
  "guest_soon": "{n} हार के बाद एक मेहमान मीनार पर आ जाता है।",
  "guest_count": "{n} में से {k} हारे — {n} हार के बाद एक मेहमान मीनार पर आ जाता है।",
  "guest_here": "आज रात एक मेहमान शूटर (ताक़त 200) पहली मंज़िल पर तुम्हारा साथ देगा।",
  "start": "रात शुरू करो",
  "swarm": "झुंड {n}",
  "py_in": "पाई: {n} में बाहर",
  "py_shell": "पाई: खोल {n}",
  "py_down": "पाई: गिरा {n} से.",
  "say_out": "पाई बाहर है — उसका खोल तोड़ो",
  "say_broke": "खोल टूट गया — एक बार और मारो",
  "say_touch": "पाई को सील करने के लिए उसे छुओ",
  "say_up": "पाई फिर उठ गया — खोल की एक परत",
  "sealed": "सील हो गया!",
  "sealed_line": "Vines तुम्हारी शेल्फ़ पर है · {n}/38। {s} से. · मीनार ने {t} गिराए, तुमने {h}।",
  "torch_out": "मशाल बुझ गई",
  "out_of_hearts": "दिल खत्म",
  "lost_line": "{s} से. · {e} ज़मीन तक पहुँचे। {guest}",
  "try_again": "फिर कोशिश करो",
  "your_house": "तुम्हारा घर",
  "move_left": "बाएँ चलो",
  "move_right": "दाएँ चलो",
  "jump": "कूदो",
  "keys_line": "← → / A D  चलो · Space ↑ W  कूदो · गिरे पाई को छुओ · Esc  रोको",
  "house_lede": "जिस भी पाई को तुम घर लाते हो, वह शेल्फ़ पर खड़ा होता है। जो फ़र्श पर चलते हैं, वे Spriteer में बनाए जाते हैं।",
  "py_counts": "पाई {a}/{b} · पालतू {c}/{d} · मछली {e}/{f}",
  "from_sp": "Spriteer से {n}",
  "none_from_sp": "Spriteer से अभी कोई नहीं",
  "door_py": "जब तक कोई रहने नहीं आता, फ़र्श खाली रहता है। spriteer.com पर चार बिंदु भरो — तुम्हारा घर तुम्हारे साथ चलता है।",
  "visit": "देखो",
  "all_nights": "ऐप में सभी 38 रातें खेलो",
  "privacy": "गोपनीयता"
 },
 "id": {
  "page_title": "Pythoneer — Satu Malam",
  "get_app": "Dapatkan aplikasinya",
  "h1": "Satu malam. Malam 4.",
  "rules_html": "Sebuah Py mendarat dan mendirikan menara. Kawanan turun dari dua sisi. <b>Jangan biarkan satu pun mencapai obor.</b> Injak mereka, atau biarkan dua temanmu di menara menembak dan membungkus mereka dengan gelembung. Saat Py keluar, pecahkan cangkangnya dua kali, lalu sentuh dia.",
  "night_name": "Malam 4 · Vine Gauntlet",
  "lose_rule": "Kalah jika ada yang mencapai obor, atau tiga hatimu habis.",
  "guest_soon": "Setelah {n} kekalahan, seorang tamu bergabung di menara.",
  "guest_count": "Kalah {k} dari {n} — setelah {n} kekalahan, seorang tamu bergabung di menara.",
  "guest_here": "Malam ini Penembak tamu (kekuatan 200) menemanimu di lantai pertama.",
  "start": "Mulai malam",
  "swarm": "Kawanan {n}",
  "py_in": "Py: keluar dalam {n}",
  "py_shell": "Py: cangkang {n}",
  "py_down": "Py: jatuh {n} dtk",
  "say_out": "Py keluar — pecahkan cangkangnya",
  "say_broke": "Cangkangnya pecah — pukul sekali lagi",
  "say_touch": "Sentuh Py untuk menyegelnya",
  "say_up": "Py bangkit lagi — satu lapis cangkang",
  "sealed": "Tersegel!",
  "sealed_line": "Vines ada di rakmu · {n}/38. {s} dtk · menara mengalahkan {t}, kamu {h}.",
  "torch_out": "Obornya padam",
  "out_of_hearts": "Hati habis",
  "lost_line": "{s} dtk · {e} mencapai tanah. {guest}",
  "try_again": "Coba lagi",
  "your_house": "Rumahmu",
  "move_left": "Gerak ke kiri",
  "move_right": "Gerak ke kanan",
  "jump": "LOMPAT",
  "keys_line": "← → / A D  Gerak · Space ↑ W  Lompat · Ketuk Py yang jatuh · Esc  Jeda",
  "house_lede": "Setiap Py yang kamu bawa pulang berdiri di rak. Yang berjalan di lantai digambar di Spriteer.",
  "py_counts": "Py {a}/{b} · Peliharaan {c}/{d} · Ikan {e}/{f}",
  "from_sp": "{n} dari Spriteer",
  "none_from_sp": "Belum ada dari Spriteer",
  "door_py": "Lantai kosong sampai ada yang pindah masuk. Isi empat titik di spriteer.com — rumahmu ikut denganmu.",
  "visit": "Kunjungi",
  "all_nights": "Mainkan 38 malam di aplikasi",
  "privacy": "Privasi"
 },
 "it": {
  "page_title": "Pythoneer — Una notte",
  "get_app": "Scarica l'app",
  "h1": "Una notte. Notte 4.",
  "rules_html": "Un Py atterra e innalza una torre. Lo sciame scende da entrambi i lati. <b>Tienili tutti lontani dalla torcia.</b> Saltagli in testa, oppure lascia che i tuoi due amici sulla torre li colpiscano e li chiudano nelle bolle. Quando il Py esce, rompigli il guscio due volte, poi toccalo.",
  "night_name": "Notte 4 · Vine Gauntlet",
  "lose_rule": "Perdi se qualcosa raggiunge la torcia o se finisci i tuoi tre cuori.",
  "guest_soon": "Dopo {n} sconfitte un ospite si unisce alla torre.",
  "guest_count": "Sconfitte: {k} su {n} — dopo {n} sconfitte un ospite si unisce alla torre.",
  "guest_here": "Stanotte un Tiratore ospite (potenza 200) si unisce a te al primo piano.",
  "start": "Inizia la notte",
  "swarm": "Sciame {n}",
  "py_in": "Py: esce tra {n}",
  "py_shell": "Py: guscio {n}",
  "py_down": "Py: a terra {n} s",
  "say_out": "Il Py è uscito — rompigli il guscio",
  "say_broke": "Il guscio si è rotto — colpiscilo ancora una volta",
  "say_touch": "Tocca il Py per sigillarlo",
  "say_up": "Il Py si è rialzato — uno strato di guscio",
  "sealed": "Sigillato!",
  "sealed_line": "Vines è sul tuo scaffale · {n}/38. {s} s · la torre ne ha presi {t}, tu {h}.",
  "torch_out": "La torcia si è spenta",
  "out_of_hearts": "Cuori finiti",
  "lost_line": "{s} s · {e} hanno toccato terra. {guest}",
  "try_again": "Riprova",
  "your_house": "La tua casa",
  "move_left": "Muovi a sinistra",
  "move_right": "Muovi a destra",
  "jump": "SALTA",
  "keys_line": "← → / A D  Muovi · Space ↑ W  Salta · Tocca il Py a terra · Esc  Pausa",
  "house_lede": "Ogni Py che porti a casa sta sullo scaffale. Quelli che camminano sul pavimento sono disegnati in Spriteer.",
  "py_counts": "Py {a}/{b} · Animali {c}/{d} · Pesci {e}/{f}",
  "from_sp": "{n} da Spriteer",
  "none_from_sp": "Ancora nessuno da Spriteer",
  "door_py": "Il pavimento resta vuoto finché qualcuno non si trasferisce. Riempi quattro punti su spriteer.com — la tua casa viene con te.",
  "visit": "Visita",
  "all_nights": "Gioca tutte le 38 notti nell'app",
  "privacy": "Privacy"
 },
 "ja": {
  "page_title": "Pythoneer — ひと晩",
  "get_app": "アプリを入手",
  "h1": "ひと晩。第4夜。",
  "rules_html": "パイが降りてきて塔を建てる。群れが両側から押し寄せる。<b>一匹もたいまつに届かせないで。</b>ふみつけるか、塔の上の2人の仲間に撃たせて泡に閉じこめよう。パイが出てきたら、殻を2回割ってからタッチ。",
  "night_name": "第4夜・Vine Gauntlet",
  "lose_rule": "何かがたいまつに届くか、3つのハートがなくなったら負け。",
  "guest_soon": "{n}回負けると、お客が塔に加わる。",
  "guest_count": "負け {k}/{n} — {n}回負けると、お客が塔に加わる。",
  "guest_here": "今夜はお客のシューター（パワー200）が1階で加勢する。",
  "start": "夜をはじめる",
  "swarm": "群れ {n}",
  "py_in": "パイ: あと{n}で出てくる",
  "py_shell": "パイ: 殻 {n}",
  "py_down": "パイ: ダウン {n}秒",
  "say_out": "パイが出た — 殻を割ろう",
  "say_broke": "殻が割れた — もう一発",
  "say_touch": "パイにタッチして封じよう",
  "say_up": "パイが起き上がった — 殻が1枚もどった",
  "sealed": "封印！",
  "sealed_line": "Vinesが棚に並んだ・{n}/38。{s}秒・塔が{t}、あなたが{h}倒した。",
  "torch_out": "たいまつが消えた",
  "out_of_hearts": "ハートがなくなった",
  "lost_line": "{s}秒・{e}匹が地面に届いた。{guest}",
  "try_again": "もう一度",
  "your_house": "あなたの家",
  "move_left": "左へ移動",
  "move_right": "右へ移動",
  "jump": "ジャンプ",
  "keys_line": "← → / A D 移動・Space ↑ W ジャンプ・倒れたパイをタップ・Esc 一時停止",
  "house_lede": "連れ帰ったパイはみんな棚に並ぶ。床を歩いているのはSpriteerで描かれたキャラ。",
  "py_counts": "パイ {a}/{b}・ペット {c}/{d}・魚 {e}/{f}",
  "from_sp": "Spriteerから{n}",
  "none_from_sp": "Spriteerからはまだ誰もいない",
  "door_py": "誰かが引っ越してくるまで床は空っぽ。spriteer.comで4つの点を塗ろう — あなたの家はどこへでも一緒。",
  "visit": "見に行く",
  "all_nights": "アプリで38夜すべてを遊ぼう",
  "privacy": "プライバシー"
 },
 "ko": {
  "page_title": "Pythoneer — 하룻밤",
  "get_app": "앱 받기",
  "h1": "하룻밤. 4번째 밤.",
  "rules_html": "파이가 내려와 탑을 세워요. 무리가 양쪽에서 몰려와요. <b>하나도 횃불에 닿지 못하게 막으세요.</b> 밟거나, 탑 위의 두 친구가 쏘고 거품에 가두게 하세요. 파이가 나오면 껍질을 두 번 깨고 터치하세요.",
  "night_name": "4번째 밤 · Vine Gauntlet",
  "lose_rule": "무엇이든 횃불에 닿거나 하트 세 개를 다 잃으면 져요.",
  "guest_soon": "{n}번 지면 손님이 탑에 합류해요.",
  "guest_count": "{n}번 중 {k}번 졌어요 — {n}번 지면 손님이 탑에 합류해요.",
  "guest_here": "오늘 밤은 손님 슈터(파워 200)가 1층에서 함께해요.",
  "start": "밤 시작하기",
  "swarm": "무리 {n}",
  "py_in": "파이: {n} 후 등장",
  "py_shell": "파이: 껍질 {n}",
  "py_down": "파이: 기절 {n}초",
  "say_out": "파이가 나왔어요 — 껍질을 깨세요",
  "say_broke": "껍질이 깨졌어요 — 한 번 더 치세요",
  "say_touch": "파이를 터치해 봉인하세요",
  "say_up": "파이가 다시 일어났어요 — 껍질 한 겹",
  "sealed": "봉인!",
  "sealed_line": "Vines가 선반에 올랐어요 · {n}/38. {s}초 · 탑이 {t}, 내가 {h} 잡았어요.",
  "torch_out": "횃불이 꺼졌어요",
  "out_of_hearts": "하트를 다 잃었어요",
  "lost_line": "{s}초 · {e}마리가 땅에 닿았어요. {guest}",
  "try_again": "다시 하기",
  "your_house": "내 집",
  "move_left": "왼쪽으로 이동",
  "move_right": "오른쪽으로 이동",
  "jump": "점프",
  "keys_line": "← → / A D 이동 · Space ↑ W 점프 · 쓰러진 파이를 탭 · Esc 일시정지",
  "house_lede": "데려온 파이는 모두 선반에 서요. 바닥을 걷는 친구들은 Spriteer에서 그려요.",
  "py_counts": "파이 {a}/{b} · 반려동물 {c}/{d} · 물고기 {e}/{f}",
  "from_sp": "Spriteer에서 온 {n}",
  "none_from_sp": "아직 Spriteer에서 온 친구가 없어요",
  "door_py": "누군가 이사 오기 전까지 바닥은 비어 있어요. spriteer.com에서 점 네 개를 채워 보세요 — 내 집은 어디든 함께 가요.",
  "visit": "놀러 가기",
  "all_nights": "앱에서 38개의 밤을 모두 플레이하세요",
  "privacy": "개인정보"
 },
 "nl": {
  "page_title": "Pythoneer — Eén nacht",
  "get_app": "Download de app",
  "h1": "Eén nacht. Nacht 4.",
  "rules_html": "Een Py landt en bouwt een toren. De zwerm komt aan beide kanten naar beneden. <b>Houd ze allemaal weg van de fakkel.</b> Spring erop, of laat je twee vrienden op de toren ze beschieten en in bellen vangen. Komt de Py naar buiten, breek dan twee keer zijn schaal en raak hem aan.",
  "night_name": "Nacht 4 · Vine Gauntlet",
  "lose_rule": "Je verliest als er iets bij de fakkel komt of als je drie hartjes op zijn.",
  "guest_soon": "Na {n} keer verliezen komt er een gast op de toren.",
  "guest_count": "{k} van {n} keer verloren — na {n} keer verliezen komt er een gast op de toren.",
  "guest_here": "Vannacht helpt een gast-Schutter (kracht 200) je op de eerste verdieping.",
  "start": "Begin de nacht",
  "swarm": "Zwerm {n}",
  "py_in": "Py: komt over {n}",
  "py_shell": "Py: schaal {n}",
  "py_down": "Py: neer {n} s",
  "say_out": "De Py is eruit — breek zijn schaal",
  "say_broke": "De schaal is gebroken — nog één keer raken",
  "say_touch": "Raak de Py aan om hem te verzegelen",
  "say_up": "De Py staat weer op — één laag schaal",
  "sealed": "Verzegeld!",
  "sealed_line": "Vines staat op je plank · {n}/38. {s} s · de toren pakte er {t}, jij {h}.",
  "torch_out": "De fakkel is uit",
  "out_of_hearts": "Geen hartjes meer",
  "lost_line": "{s} s · {e} bereikten de grond. {guest}",
  "try_again": "Opnieuw",
  "your_house": "Jouw huis",
  "move_left": "Naar links",
  "move_right": "Naar rechts",
  "jump": "SPRING",
  "keys_line": "← → / A D  Lopen · Space ↑ W  Springen · Tik op de gevallen Py · Esc  Pauze",
  "house_lede": "Elke Py die je mee naar huis neemt, staat op de plank. Wie over de vloer loopt, is getekend in Spriteer.",
  "py_counts": "Py's {a}/{b} · Huisdieren {c}/{d} · Vissen {e}/{f}",
  "from_sp": "{n} uit Spriteer",
  "none_from_sp": "Nog niemand uit Spriteer",
  "door_py": "De vloer blijft leeg tot er iemand intrekt. Vul vier punten op spriteer.com — je huis gaat met je mee.",
  "visit": "Bezoeken",
  "all_nights": "Speel alle 38 nachten in de app",
  "privacy": "Privacy"
 },
 "pt-BR": {
  "page_title": "Pythoneer — Uma noite",
  "get_app": "Baixe o app",
  "h1": "Uma noite. Noite 4.",
  "rules_html": "Um Py pousa e ergue uma torre. O enxame desce pelos dois lados. <b>Não deixe nenhum chegar à tocha.</b> Pule neles ou deixe seus dois amigos na torre atirarem e prendê-los em bolhas. Quando o Py sair, quebre a casca dele duas vezes e depois toque nele.",
  "night_name": "Noite 4 · Vine Gauntlet",
  "lose_rule": "Você perde se algo chegar à tocha ou se seus três corações acabarem.",
  "guest_soon": "Depois de {n} derrotas, uma visita entra na torre.",
  "guest_count": "{k} de {n} derrotas — depois de {n} derrotas, uma visita entra na torre.",
  "guest_here": "Hoje à noite um Atirador visitante (poder 200) se junta a você no primeiro andar.",
  "start": "Começar a noite",
  "swarm": "Enxame {n}",
  "py_in": "Py: sai em {n}",
  "py_shell": "Py: casca {n}",
  "py_down": "Py: caído {n} s",
  "say_out": "O Py saiu — quebre a casca",
  "say_broke": "A casca quebrou — acerte mais uma vez",
  "say_touch": "Toque no Py para selá-lo",
  "say_up": "O Py se levantou — uma camada de casca",
  "sealed": "Selado!",
  "sealed_line": "Vines está na sua estante · {n}/38. {s} s · a torre pegou {t}, você pegou {h}.",
  "torch_out": "A tocha apagou",
  "out_of_hearts": "Sem corações",
  "lost_line": "{s} s · {e} chegaram ao chão. {guest}",
  "try_again": "Tentar de novo",
  "your_house": "Sua casa",
  "move_left": "Mover para a esquerda",
  "move_right": "Mover para a direita",
  "jump": "PULAR",
  "keys_line": "← → / A D  Mover · Space ↑ W  Pular · Toque no Py caído · Esc  Pausar",
  "house_lede": "Todo Py que você leva para casa fica na estante. Quem anda pelo chão é desenhado no Spriteer.",
  "py_counts": "Pys {a}/{b} · Bichos {c}/{d} · Peixes {e}/{f}",
  "from_sp": "{n} do Spriteer",
  "none_from_sp": "Ninguém do Spriteer ainda",
  "door_py": "O chão fica vazio até alguém se mudar. Preencha quatro pontos em spriteer.com — sua casa vai com você.",
  "visit": "Visitar",
  "all_nights": "Jogue as 38 noites no app",
  "privacy": "Privacidade"
 },
 "ru": {
  "page_title": "Pythoneer — Одна ночь",
  "get_app": "Скачать приложение",
  "h1": "Одна ночь. Ночь 4.",
  "rules_html": "Пай приземляется и возводит башню. Рой спускается с обеих сторон. <b>Не подпусти ни одного к факелу.</b> Прыгай им на головы или дай двум друзьям на башне стрелять и запирать их в пузыри. Когда Пай выйдет, дважды расколи его панцирь, а потом коснись его.",
  "night_name": "Ночь 4 · Vine Gauntlet",
  "lose_rule": "Проигрыш, если кто-то доберётся до факела или кончатся три сердца.",
  "guest_soon": "После {n} поражений на башню придёт гость.",
  "guest_count": "Поражений: {k} из {n} — после {n} поражений на башню придёт гость.",
  "guest_here": "Сегодня на первом этаже тебе поможет гость-Стрелок (сила 200).",
  "start": "Начать ночь",
  "swarm": "Рой {n}",
  "py_in": "Пай: выйдет через {n}",
  "py_shell": "Пай: панцирь {n}",
  "py_down": "Пай: повержен {n} с",
  "say_out": "Пай вышел — расколи панцирь",
  "say_broke": "Панцирь треснул — ударь ещё раз",
  "say_touch": "Коснись Пая, чтобы запечатать его",
  "say_up": "Пай поднялся — один слой панциря",
  "sealed": "Запечатан!",
  "sealed_line": "Vines на твоей полке · {n}/38. {s} с · башня взяла {t}, ты — {h}.",
  "torch_out": "Факел погас",
  "out_of_hearts": "Сердца кончились",
  "lost_line": "{s} с · до земли добралось: {e}. {guest}",
  "try_again": "Ещё раз",
  "your_house": "Твой дом",
  "move_left": "Влево",
  "move_right": "Вправо",
  "jump": "ПРЫЖОК",
  "keys_line": "← → / A D  Ходить · Space ↑ W  Прыжок · Коснись поверженного Пая · Esc  Пауза",
  "house_lede": "Каждый Пай, которого ты приводишь домой, стоит на полке. Тех, кто ходит по полу, рисуют в Spriteer.",
  "py_counts": "Паи {a}/{b} · Питомцы {c}/{d} · Рыбы {e}/{f}",
  "from_sp": "Из Spriteer: {n}",
  "none_from_sp": "Из Spriteer пока никого",
  "door_py": "Пол пустует, пока кто-нибудь не переедет. Заполни четыре точки на spriteer.com — твой дом всегда с тобой.",
  "visit": "В гости",
  "all_nights": "Все 38 ночей — в приложении",
  "privacy": "Конфиденциальность"
 },
 "sv": {
  "page_title": "Pythoneer — En natt",
  "get_app": "Hämta appen",
  "h1": "En natt. Natt 4.",
  "rules_html": "En Py landar och reser ett torn. Svärmen kommer ner på båda sidor. <b>Håll var och en borta från facklan.</b> Hoppa på dem, eller låt dina två vänner i tornet skjuta och bubbla in dem. När Py kommer ut, knäck skalet två gånger och rör sedan vid den.",
  "night_name": "Natt 4 · Vine Gauntlet",
  "lose_rule": "Du förlorar om något når facklan eller om dina tre hjärtan tar slut.",
  "guest_soon": "Efter {n} förluster kommer en gäst till tornet.",
  "guest_count": "Förlorat {k} av {n} — efter {n} förluster kommer en gäst till tornet.",
  "guest_here": "En gästskytt (kraft 200) är med dig på första våningen i natt.",
  "start": "Starta natten",
  "swarm": "Svärm {n}",
  "py_in": "Py: kommer ut om {n}",
  "py_shell": "Py: skal {n}",
  "py_down": "Py: nere {n} s",
  "say_out": "Py är ute — knäck skalet",
  "say_broke": "Skalet sprack — slå en gång till",
  "say_touch": "Rör vid Py för att försegla den",
  "say_up": "Py reste sig igen — ett lager skal",
  "sealed": "Förseglad!",
  "sealed_line": "Vines står på din hylla · {n}/38. {s} s · tornet fällde {t}, du fällde {h}.",
  "torch_out": "Facklan slocknade",
  "out_of_hearts": "Slut på hjärtan",
  "lost_line": "{s} s · {e} nådde marken. {guest}",
  "try_again": "Försök igen",
  "your_house": "Ditt hus",
  "move_left": "Gå vänster",
  "move_right": "Gå höger",
  "jump": "HOPPA",
  "keys_line": "← → / A D  Gå · Space ↑ W  Hoppa · Tryck på den fällda Py · Esc  Paus",
  "house_lede": "Varje Py du tar hem står på hyllan. De som går på golvet är ritade i Spriteer.",
  "py_counts": "Py {a}/{b} · Husdjur {c}/{d} · Fiskar {e}/{f}",
  "from_sp": "{n} från Spriteer",
  "none_from_sp": "Ingen från Spriteer än",
  "door_py": "Golvet är tomt tills någon flyttar in. Fyll fyra prickar på spriteer.com — ditt hus följer med dig.",
  "visit": "Besök",
  "all_nights": "Spela alla 38 nätter i appen",
  "privacy": "Integritet"
 },
 "th": {
  "page_title": "Pythoneer — หนึ่งคืน",
  "get_app": "ดาวน์โหลดแอป",
  "h1": "หนึ่งคืน คืนที่ 4",
  "rules_html": "ไพตัวหนึ่งลงมาและสร้างหอคอย ฝูงศัตรูบุกลงมาทั้งสองฝั่ง <b>อย่าให้ตัวไหนไปถึงคบเพลิง</b> เหยียบพวกมัน หรือให้เพื่อนสองคนบนหอคอยยิงและเป่าฟองขังไว้ เมื่อไพออกมา ทุบเปลือกมันสองครั้ง แล้วแตะมัน",
  "night_name": "คืนที่ 4 · Vine Gauntlet",
  "lose_rule": "แพ้ถ้ามีอะไรไปถึงคบเพลิง หรือหัวใจทั้งสามดวงหมด",
  "guest_soon": "แพ้ครบ {n} ครั้ง จะมีแขกมาช่วยบนหอคอย",
  "guest_count": "แพ้ไป {k} จาก {n} — แพ้ครบ {n} ครั้ง จะมีแขกมาช่วยบนหอคอย",
  "guest_here": "คืนนี้มีแขกนักยิง (พลัง 200) มาช่วยคุณที่ชั้นหนึ่ง",
  "start": "เริ่มคืนนี้",
  "swarm": "ฝูง {n}",
  "py_in": "ไพ: ออกมาใน {n}",
  "py_shell": "ไพ: เปลือก {n}",
  "py_down": "ไพ: ล้มอยู่ {n} วิ",
  "say_out": "ไพออกมาแล้ว — ทุบเปลือกมัน",
  "say_broke": "เปลือกแตกแล้ว — ตีอีกครั้ง",
  "say_touch": "แตะไพเพื่อผนึกมัน",
  "say_up": "ไพลุกขึ้นมาอีก — เหลือเปลือกหนึ่งชั้น",
  "sealed": "ผนึกแล้ว!",
  "sealed_line": "Vines อยู่บนชั้นของคุณแล้ว · {n}/38 {s} วิ · หอคอยจัดการได้ {t} คุณจัดการได้ {h}",
  "torch_out": "คบเพลิงดับแล้ว",
  "out_of_hearts": "หัวใจหมดแล้ว",
  "lost_line": "{s} วิ · {e} ตัวถึงพื้น {guest}",
  "try_again": "ลองอีกครั้ง",
  "your_house": "บ้านของคุณ",
  "move_left": "ไปซ้าย",
  "move_right": "ไปขวา",
  "jump": "กระโดด",
  "keys_line": "← → / A D  เดิน · Space ↑ W  กระโดด · แตะไพที่ล้มอยู่ · Esc  พัก",
  "house_lede": "ไพทุกตัวที่คุณพากลับบ้านจะยืนอยู่บนชั้นวาง ส่วนตัวที่เดินบนพื้นวาดใน Spriteer",
  "py_counts": "ไพ {a}/{b} · สัตว์เลี้ยง {c}/{d} · ปลา {e}/{f}",
  "from_sp": "{n} จาก Spriteer",
  "none_from_sp": "ยังไม่มีใครจาก Spriteer",
  "door_py": "พื้นจะว่างจนกว่าจะมีใครย้ายเข้ามา เติมสี่จุดที่ spriteer.com — บ้านของคุณไปกับคุณทุกที่",
  "visit": "แวะไปดู",
  "all_nights": "เล่นครบ 38 คืนในแอป",
  "privacy": "ความเป็นส่วนตัว"
 },
 "tr": {
  "page_title": "Pythoneer — Bir Gece",
  "get_app": "Uygulamayı indir",
  "h1": "Bir gece. 4. gece.",
  "rules_html": "Bir Py iner ve bir kule kurar. Sürü iki yandan aşağı iner. <b>Hiçbirini meşaleye yaklaştırma.</b> Üstlerine zıpla ya da kuledeki iki arkadaşın ateş edip onları baloncuğa hapsetsin. Py dışarı çıkınca kabuğunu iki kez kır, sonra ona dokun.",
  "night_name": "4. gece · Vine Gauntlet",
  "lose_rule": "Meşaleye bir şey ulaşırsa ya da üç kalbin biterse kaybedersin.",
  "guest_soon": "{n} yenilgiden sonra kuleye bir misafir katılır.",
  "guest_count": "{k}/{n} yenilgi — {n} yenilgiden sonra kuleye bir misafir katılır.",
  "guest_here": "Bu gece birinci katta sana misafir bir Nişancı (güç 200) katılıyor.",
  "start": "Geceyi başlat",
  "swarm": "Sürü {n}",
  "py_in": "Py: çıkmasına {n}",
  "py_shell": "Py: kabuk {n}",
  "py_down": "Py: yerde {n} sn",
  "say_out": "Py dışarıda — kabuğunu kır",
  "say_broke": "Kabuk kırıldı — bir kez daha vur",
  "say_touch": "Py yerde — dokun ve mühürle",
  "say_up": "Py yeniden kalktı — tek kat kabuk",
  "sealed": "Mühürlendi!",
  "sealed_line": "Vines rafında · {n}/38. {s} sn · kule {t}, sen {h} tane indirdin.",
  "torch_out": "Meşale söndü",
  "out_of_hearts": "Kalp kalmadı",
  "lost_line": "{s} sn · {e} tanesi yere ulaştı. {guest}",
  "try_again": "Tekrar dene",
  "your_house": "Evin",
  "move_left": "Sola git",
  "move_right": "Sağa git",
  "jump": "ZIPLA",
  "keys_line": "← → / A D  Yürü · Space ↑ W  Zıpla · Yerdeki Py: dokun · Esc  Duraklat",
  "house_lede": "Eve getirdiğin her Py rafta durur. Yerde yürüyenler Spriteer'da çizilir.",
  "py_counts": "Py {a}/{b} · Evcil {c}/{d} · Balık {e}/{f}",
  "from_sp": "Spriteer'dan {n}",
  "none_from_sp": "Henüz Spriteer'dan kimse yok",
  "door_py": "Biri taşınana kadar zemin boş kalır. spriteer.com'da dört noktayı doldur — evin seninle gelir.",
  "visit": "Ziyaret et",
  "all_nights": "38 gecenin hepsini uygulamada oyna",
  "privacy": "Gizlilik"
 },
 "vi": {
  "page_title": "Pythoneer — Một đêm",
  "get_app": "Tải ứng dụng",
  "h1": "Một đêm. Đêm 4.",
  "rules_html": "Một Py đáp xuống và dựng tháp. Bầy quái tràn xuống cả hai bên. <b>Đừng để con nào chạm tới ngọn đuốc.</b> Nhảy lên đầu chúng, hoặc để hai người bạn trên tháp bắn và nhốt chúng vào bong bóng. Khi Py ra ngoài, đập vỡ vỏ nó hai lần, rồi chạm vào nó.",
  "night_name": "Đêm 4 · Vine Gauntlet",
  "lose_rule": "Thua nếu có thứ gì chạm tới ngọn đuốc, hoặc bạn hết ba trái tim.",
  "guest_soon": "Sau {n} lần thua, một vị khách sẽ lên tháp cùng bạn.",
  "guest_count": "Đã thua {k}/{n} — sau {n} lần thua, một vị khách sẽ lên tháp cùng bạn.",
  "guest_here": "Đêm nay một Xạ thủ khách (sức mạnh 200) cùng bạn ở tầng một.",
  "start": "Bắt đầu đêm",
  "swarm": "Bầy {n}",
  "py_in": "Py: ra sau {n}",
  "py_shell": "Py: vỏ {n}",
  "py_down": "Py: ngã {n} giây",
  "say_out": "Py đã ra — đập vỡ vỏ nó",
  "say_broke": "Vỏ đã vỡ — đánh thêm một lần",
  "say_touch": "Chạm vào Py để phong ấn",
  "say_up": "Py đứng dậy rồi — còn một lớp vỏ",
  "sealed": "Đã phong ấn!",
  "sealed_line": "Vines đã lên kệ của bạn · {n}/38. {s} giây · tháp hạ {t}, bạn hạ {h}.",
  "torch_out": "Ngọn đuốc đã tắt",
  "out_of_hearts": "Hết tim",
  "lost_line": "{s} giây · {e} con chạm đất. {guest}",
  "try_again": "Thử lại",
  "your_house": "Nhà của bạn",
  "move_left": "Sang trái",
  "move_right": "Sang phải",
  "jump": "NHẢY",
  "keys_line": "← → / A D  Di chuyển · Space ↑ W  Nhảy · Chạm vào Py đang ngã · Esc  Tạm dừng",
  "house_lede": "Mỗi Py bạn mang về đều đứng trên kệ. Những ai đi lại trên sàn được vẽ trong Spriteer.",
  "py_counts": "Py {a}/{b} · Thú cưng {c}/{d} · Cá {e}/{f}",
  "from_sp": "{n} từ Spriteer",
  "none_from_sp": "Chưa có ai từ Spriteer",
  "door_py": "Sàn nhà trống cho đến khi có ai dọn vào. Tô bốn chấm ở spriteer.com — ngôi nhà luôn đi cùng bạn.",
  "visit": "Ghé thăm",
  "all_nights": "Chơi đủ 38 đêm trong ứng dụng",
  "privacy": "Quyền riêng tư"
 },
 "zh-Hans": {
  "page_title": "Pythoneer — 一夜",
  "get_app": "获取 App",
  "h1": "一夜。第 4 夜。",
  "rules_html": "一只派落下，升起一座塔。怪群从两边涌下来。<b>别让任何一只碰到火炬。</b>踩它们，或让塔上的两个朋友射击、用泡泡困住它们。派出来后，敲破它的壳两次，然后碰它一下。",
  "night_name": "第 4 夜 · Vine Gauntlet",
  "lose_rule": "有东西碰到火炬，或三颗心用完，就输了。",
  "guest_soon": "输 {n} 次后，会有一位客人来塔上帮忙。",
  "guest_count": "已输 {k}/{n} 次——输 {n} 次后，会有一位客人来塔上帮忙。",
  "guest_here": "今晚有一位客人射手（力量 200）在一楼和你并肩作战。",
  "start": "开始这一夜",
  "swarm": "怪群 {n}",
  "py_in": "派：{n} 后出来",
  "py_shell": "派：壳 {n}",
  "py_down": "派：倒地 {n} 秒",
  "say_out": "派出来了——敲破它的壳",
  "say_broke": "壳破了——再打一下",
  "say_touch": "碰一下派，把它封印",
  "say_up": "派又站起来了——还剩一层壳",
  "sealed": "封印了！",
  "sealed_line": "Vines 上了你的架子 · {n}/38。{s} 秒 · 塔打倒 {t}，你打倒 {h}。",
  "torch_out": "火炬熄灭了",
  "out_of_hearts": "心用完了",
  "lost_line": "{s} 秒 · {e} 只落到了地面。{guest}",
  "try_again": "再试一次",
  "your_house": "你的家",
  "move_left": "向左",
  "move_right": "向右",
  "jump": "跳",
  "keys_line": "← → / A D 移动 · Space ↑ W 跳 · 点按倒地的派 · Esc 暂停",
  "house_lede": "你带回家的每只派都站在架子上。在地板上走动的角色是在 Spriteer 里画的。",
  "py_counts": "派 {a}/{b} · 宠物 {c}/{d} · 鱼 {e}/{f}",
  "from_sp": "{n} 位来自 Spriteer",
  "none_from_sp": "还没有来自 Spriteer 的角色",
  "door_py": "有人搬进来之前，地板是空的。到 spriteer.com 填上四个点——你的家跟着你走。",
  "visit": "去看看",
  "all_nights": "在 App 中玩全部 38 夜",
  "privacy": "隐私"
 },
 "zh-Hant": {
  "page_title": "Pythoneer — 一夜",
  "get_app": "取得 App",
  "h1": "一夜。第 4 夜。",
  "rules_html": "一隻派落下，升起一座塔。怪群從兩邊湧下來。<b>別讓任何一隻碰到火炬。</b>踩牠們，或讓塔上的兩個朋友射擊、用泡泡困住牠們。派出來後，敲破牠的殼兩次，然後碰牠一下。",
  "night_name": "第 4 夜 · Vine Gauntlet",
  "lose_rule": "有東西碰到火炬，或三顆心用完，就輸了。",
  "guest_soon": "輸 {n} 次後，會有一位客人來塔上幫忙。",
  "guest_count": "已輸 {k}/{n} 次——輸 {n} 次後，會有一位客人來塔上幫忙。",
  "guest_here": "今晚有一位客人射手（力量 200）在一樓和你並肩作戰。",
  "start": "開始這一夜",
  "swarm": "怪群 {n}",
  "py_in": "派：{n} 後出來",
  "py_shell": "派：殼 {n}",
  "py_down": "派：倒地 {n} 秒",
  "say_out": "派出來了——敲破牠的殼",
  "say_broke": "殼破了——再打一下",
  "say_touch": "碰一下派，把牠封印",
  "say_up": "派又站起來了——還剩一層殼",
  "sealed": "封印了！",
  "sealed_line": "Vines 上了你的架子 · {n}/38。{s} 秒 · 塔打倒 {t}，你打倒 {h}。",
  "torch_out": "火炬熄滅了",
  "out_of_hearts": "心用完了",
  "lost_line": "{s} 秒 · {e} 隻落到了地面。{guest}",
  "try_again": "再試一次",
  "your_house": "你的家",
  "move_left": "向左",
  "move_right": "向右",
  "jump": "跳",
  "keys_line": "← → / A D 移動 · Space ↑ W 跳 · 點一下倒地的派 · Esc 暫停",
  "house_lede": "你帶回家的每隻派都站在架子上。在地板上走動的角色是在 Spriteer 裡畫的。",
  "py_counts": "派 {a}/{b} · 寵物 {c}/{d} · 魚 {e}/{f}",
  "from_sp": "{n} 位來自 Spriteer",
  "none_from_sp": "還沒有來自 Spriteer 的角色",
  "door_py": "有人搬進來之前，地板是空的。到 spriteer.com 填上四個點——你的家跟著你走。",
  "visit": "去看看",
  "all_nights": "在 App 中玩全部 38 夜",
  "privacy": "隱私權"
 }
};
