// Generated from the translators' JSON (en + 18) by scratchpad i18n/merge.py. Do not edit by hand.
export const STRINGS = {
 "en": {
  "page_title": "Pythoneer — One Night",
  "get_app": "Get the app",
  "h1": "One night. Night 4.",
  "rules_html": "A Py lands and raises a tower. The swarm comes down both sides. <b>Keep every one of them off the torch.</b> Stomp them, or let your two friends on the tower shoot and bubble them. When the Py comes out, crack its shell twice, then touch it.",
  "night_name": "Night 4 · Vine Gauntlet",
  "lose_rule": "Lose if anything reaches the torch, or your three hearts run out.",
  "guest_soon": "After {n} losses a guest joins the tower.",
  "guest_count": "Lost {k} of {n} — after {n} losses a guest joins the tower.",
  "guest_here": "A guest Shooter (power 200) joins you on the first floor tonight.",
  "start": "Start the night",
  "swarm": "Swarm {n}",
  "py_in": "Py: comes out in {n}",
  "py_shell": "Py: shell {n}",
  "py_down": "Py: down {n}s",
  "say_out": "The Py is out — crack its shell",
  "say_broke": "The shell broke — hit it once more",
  "say_touch": "Touch the Py to seal it",
  "say_up": "The Py got back up — one shell layer",
  "sealed": "Sealed!",
  "sealed_line": "Vines is on your shelf · {n}/38. {s}s · the tower took {t}, you took {h}.",
  "torch_out": "The torch went out",
  "out_of_hearts": "Out of hearts",
  "lost_line": "{s}s · {e} reached the ground. {guest}",
  "try_again": "Try again",
  "your_house": "Your house",
  "move_left": "Move left",
  "move_right": "Move right",
  "jump": "JUMP",
  "keys_line": "← → / A D  Move · Space ↑ W  Jump · Tap the downed Py · Esc  Pause",
  "house_lede": "Every Py you bring home stands on the shelf. The ones who walk the floor are drawn in Spriteer.",
  "py_counts": "Pys {a}/{b} · Pets {c}/{d} · Fish {e}/{f}",
  "from_sp": "{n} from Spriteer",
  "none_from_sp": "No one from Spriteer yet",
  "door_py": "The floor is empty until someone moves in. Fill four dots at spriteer.com — your house goes with you.",
  "visit": "Visit",
  "all_nights": "Play all 38 nights in the app",
  "privacy": "Privacy"
 },
 "ar": {
  "page_title": "Pythoneer — ليلة واحدة",
  "get_app": "حمّل التطبيق",
  "h1": "ليلة واحدة. الليلة الرابعة.",
  "rules_html": "يهبط باي ويرفع برجًا، وينقضّ السرب من الجانبين. <b>لا تدع واحدًا منهم يبلغ الشعلة.</b> اقفز فوقهم، أو دع صديقَيك على البرج يرميانهم ويحبسانهم في فقاعات. وحين يخرج الباي، اكسر قوقعته مرتين ثم المسه.",
  "night_name": "الليلة 4 · Vine Gauntlet",
  "lose_rule": "تخسر إن بلغ أيّ شيء الشعلة، أو نفدت قلوبك الثلاثة.",
  "guest_soon": "بعد {n} خسارات ينضمّ ضيف إلى البرج.",
  "guest_count": "خسرت {k} من {n} — بعد {n} خسارات ينضمّ ضيف إلى البرج.",
  "guest_here": "الليلة ينضمّ إليك رامٍ ضيف (قوة 200) في الطابق الأول.",
  "start": "ابدأ الليلة",
  "swarm": "السرب {n}",
  "py_in": "باي: يخرج بعد {n}",
  "py_shell": "باي: القوقعة {n}",
  "py_down": "باي: ساقط {n} ث",
  "say_out": "خرج الباي — اكسر قوقعته",
  "say_broke": "انكسرت القوقعة — اضربه مرة أخرى",
  "say_touch": "المس الباي لتختمه",
  "say_up": "نهض الباي من جديد — بطبقة قوقعة واحدة",
  "sealed": "تم الختم!",
  "sealed_line": "Vines على رفّك الآن · {n}/38. {s} ث · أسقط البرج {t}، وأسقطتَ أنت {h}.",
  "torch_out": "انطفأت الشعلة",
  "out_of_hearts": "نفدت القلوب",
  "lost_line": "{s} ث · وصل {e} إلى الأرض. {guest}",
  "try_again": "أعد المحاولة",
  "your_house": "بيتك",
  "move_left": "تحرّك يسارًا",
  "move_right": "تحرّك يمينًا",
  "jump": "اقفز",
  "keys_line": "← → / A D  تحرّك · Space ↑ W  اقفز · المس الباي الساقط · Esc  إيقاف مؤقت",
  "house_lede": "كل باي تعيده إلى البيت يقف على الرف. أما من يتجوّلون على الأرضية فمرسومون في Spriteer.",
  "py_counts": "باي {a}/{b} · حيوانات أليفة {c}/{d} · أسماك {e}/{f}",
  "from_sp": "{n} من Spriteer",
  "none_from_sp": "لا أحد من Spriteer بعد",
  "door_py": "الأرضية خالية حتى يسكنها أحد. لوّن أربع نقاط على spriteer.com — وبيتك يرافقك أينما ذهبت.",
  "visit": "زيارة",
  "all_nights": "العب الليالي الـ38 كلها في التطبيق",
  "privacy": "الخصوصية"
 },
 "de": {
  "page_title": "Pythoneer — Eine Nacht",
  "get_app": "App laden",
  "h1": "Eine Nacht. Nacht 4.",
  "rules_html": "Ein Py landet und baut einen Turm. Der Schwarm kommt auf beiden Seiten herab. <b>Keiner von ihnen darf an die Fackel.</b> Spring ihnen auf den Kopf – oder lass deine zwei Freunde auf dem Turm schießen und sie in Blasen einschließen. Kommt der Py heraus, knack zweimal seine Schale und berühr ihn dann.",
  "night_name": "Nacht 4 · Vine Gauntlet",
  "lose_rule": "Verloren, wenn etwas die Fackel erreicht oder deine drei Herzen aufgebraucht sind.",
  "guest_soon": "Nach {n} Niederlagen kommt ein Gast auf den Turm.",
  "guest_count": "{k} von {n} verloren — nach {n} Niederlagen kommt ein Gast auf den Turm.",
  "guest_here": "Heute Nacht steht dir ein Gast-Schütze (Stärke 200) im ersten Stock zur Seite.",
  "start": "Nacht starten",
  "swarm": "Schwarm {n}",
  "py_in": "Py: erscheint in {n}",
  "py_shell": "Py: Schale {n}",
  "py_down": "Py: am Boden {n} s",
  "say_out": "Der Py ist draußen — knack seine Schale",
  "say_broke": "Schale geknackt — noch ein Treffer",
  "say_touch": "Berühr den Py, um ihn zu versiegeln",
  "say_up": "Der Py ist wieder auf den Beinen — eine Schicht Schale",
  "sealed": "Versiegelt!",
  "sealed_line": "Vines steht jetzt in deinem Regal · {n}/38. {s} s · der Turm hat {t} erledigt, du {h}.",
  "torch_out": "Die Fackel ist erloschen",
  "out_of_hearts": "Keine Herzen mehr",
  "lost_line": "{s} s · Am Boden angekommen: {e}. {guest}",
  "try_again": "Noch mal",
  "your_house": "Dein Haus",
  "move_left": "Nach links",
  "move_right": "Nach rechts",
  "jump": "SPRUNG",
  "keys_line": "← → / A D  Laufen · Space ↑ W  Springen · Liegenden Py antippen · Esc  Pause",
  "house_lede": "Jeder Py, den du nach Hause bringst, steht im Regal. Wer über den Boden läuft, wurde in Spriteer gezeichnet.",
  "py_counts": "Pys {a}/{b} · Haustiere {c}/{d} · Fische {e}/{f}",
  "from_sp": "{n} aus Spriteer",
  "none_from_sp": "Noch niemand aus Spriteer",
  "door_py": "Der Boden bleibt leer, bis jemand einzieht. Mal auf spriteer.com vier Punkte aus — dein Haus kommt überallhin mit.",
  "visit": "Besuchen",
  "all_nights": "Alle 38 Nächte in der App spielen",
  "privacy": "Datenschutz"
 },
 "es": {
  "page_title": "Pythoneer — Una noche",
  "get_app": "Descargar la app",
  "h1": "Una noche. Noche 4.",
  "rules_html": "Un Py aterriza y levanta una torre. El enjambre baja por ambos lados. <b>Que ninguno llegue a la antorcha.</b> Písalos, o deja que tus dos amigos de la torre les disparen y los encierren en burbujas. Cuando salga el Py, rómpele el caparazón dos veces y luego tócalo.",
  "night_name": "Noche 4 · Vine Gauntlet",
  "lose_rule": "Pierdes si algo llega a la antorcha o se te acaban los tres corazones.",
  "guest_soon": "Tras {n} derrotas, se une un invitado a la torre.",
  "guest_count": "Perdiste {k} de {n} — tras {n} derrotas, se une un invitado a la torre.",
  "guest_here": "Esta noche te acompaña un Tirador invitado (poder 200) en el primer piso.",
  "start": "Empezar la noche",
  "swarm": "Enjambre {n}",
  "py_in": "Py: sale en {n}",
  "py_shell": "Py: caparazón {n}",
  "py_down": "Py: caído {n} s",
  "say_out": "El Py salió — rómpele el caparazón",
  "say_broke": "Caparazón roto — dale una vez más",
  "say_touch": "Toca al Py para sellarlo",
  "say_up": "El Py se levantó — con una capa de caparazón",
  "sealed": "¡Sellado!",
  "sealed_line": "Vines ya está en tu estante · {n}/38. {s} s · la torre acabó con {t}, tú con {h}.",
  "torch_out": "La antorcha se apagó",
  "out_of_hearts": "Sin corazones",
  "lost_line": "{s} s · Llegaron al suelo: {e}. {guest}",
  "try_again": "Reintentar",
  "your_house": "Tu casa",
  "move_left": "Mover a la izquierda",
  "move_right": "Mover a la derecha",
  "jump": "SALTAR",
  "keys_line": "← → / A D  Mover · Space ↑ W  Saltar · Toca al Py caído · Esc  Pausa",
  "house_lede": "Cada Py que traes a casa queda en el estante. Los que andan por el suelo están dibujados en Spriteer.",
  "py_counts": "Pys {a}/{b} · Mascotas {c}/{d} · Peces {e}/{f}",
  "from_sp": "{n} de Spriteer",
  "none_from_sp": "Aún nadie de Spriteer",
  "door_py": "El suelo está vacío hasta que alguien se instale. Colorea cuatro puntos en spriteer.com: tu casa va contigo.",
  "visit": "Visitar",
  "all_nights": "Juega las 38 noches en la app",
  "privacy": "Privacidad"
 },
 "fr": {
  "page_title": "Pythoneer — Une nuit",
  "get_app": "Télécharger l'app",
  "h1": "Une nuit. Nuit 4.",
  "rules_html": "Un Py atterrit et dresse une tour. La nuée descend des deux côtés. <b>Qu'aucun n'atteigne la torche.</b> Sautez-leur dessus, ou laissez vos deux amis de la tour leur tirer dessus et les piéger dans des bulles. Quand le Py sort, brisez deux fois sa carapace, puis touchez-le.",
  "night_name": "Nuit 4 · Vine Gauntlet",
  "lose_rule": "Défaite si quoi que ce soit atteint la torche, ou si vos trois cœurs sont épuisés.",
  "guest_soon": "Après {n} défaites, un invité rejoint la tour.",
  "guest_count": "Défaites : {k} sur {n} — après {n} défaites, un invité rejoint la tour.",
  "guest_here": "Cette nuit, un Tireur invité (puissance 200) vous rejoint au premier étage.",
  "start": "Commencer la nuit",
  "swarm": "Nuée {n}",
  "py_in": "Py : sort dans {n}",
  "py_shell": "Py : carapace {n}",
  "py_down": "Py : à terre {n} s",
  "say_out": "Le Py est sorti — brisez sa carapace",
  "say_broke": "Carapace brisée — encore un coup",
  "say_touch": "Touchez le Py pour le sceller",
  "say_up": "Le Py s'est relevé — avec une couche de carapace",
  "sealed": "Scellé !",
  "sealed_line": "Vines rejoint votre étagère · {n}/38. {s} s · la tour en a eu {t}, vous {h}.",
  "torch_out": "La torche s'est éteinte",
  "out_of_hearts": "Plus de cœurs",
  "lost_line": "{s} s · Arrivés au sol : {e}. {guest}",
  "try_again": "Réessayer",
  "your_house": "Votre maison",
  "move_left": "Aller à gauche",
  "move_right": "Aller à droite",
  "jump": "SAUT",
  "keys_line": "← → / A D  Bouger · Space ↑ W  Sauter · Touchez le Py à terre · Esc  Pause",
  "house_lede": "Chaque Py que vous ramenez prend place sur l'étagère. Ceux qui se promènent au sol sont dessinés dans Spriteer.",
  "py_counts": "Pys {a}/{b} · Animaux {c}/{d} · Poissons {e}/{f}",
  "from_sp": "{n} de Spriteer",
  "none_from_sp": "Personne de Spriteer pour l'instant",
  "door_py": "Le sol reste vide tant que personne n'emménage. Coloriez quatre points sur spriteer.com — votre maison vous suit.",
  "visit": "Visiter",
  "all_nights": "Jouez les 38 nuits dans l'app",
  "privacy": "Confidentialité"
 },
 "hi": {
  "page_title": "Pythoneer — एक रात",
  "get_app": "ऐप डाउनलोड करें",
  "h1": "एक रात। रात 4।",
  "rules_html": "एक पाई उतरता है और एक मीनार खड़ी करता है। झुंड दोनों ओर से नीचे आता है। <b>एक को भी मशाल तक न पहुँचने दीजिए।</b> उन पर कूदकर कुचलिए, या मीनार पर बैठे अपने दो दोस्तों को उन पर निशाना साधने और उन्हें बुलबुलों में क़ैद करने दीजिए। पाई बाहर आए तो उसका खोल दो बार तोड़िए, फिर उसे छू लीजिए।",
  "night_name": "रात 4 · Vine Gauntlet",
  "lose_rule": "अगर कुछ भी मशाल तक पहुँचा, या आपके तीनों दिल ख़त्म हुए, तो आप हार जाएँगे।",
  "guest_soon": "{n} बार हारने पर एक मेहमान मीनार पर आ जाता है।",
  "guest_count": "{n} में से {k} बार हारे — {n} बार हारने पर एक मेहमान मीनार पर आ जाता है।",
  "guest_here": "आज रात एक मेहमान शूटर (ताक़त 200) पहली मंज़िल पर आपका साथ देगा।",
  "start": "रात शुरू करें",
  "swarm": "झुंड {n}",
  "py_in": "पाई: {n} में बाहर",
  "py_shell": "पाई: खोल {n}",
  "py_down": "पाई: गिरा {n} से.",
  "say_out": "पाई बाहर आ गया — उसका खोल तोड़िए",
  "say_broke": "खोल टूट गया — एक वार और",
  "say_touch": "सील करने के लिए पाई को छुइए",
  "say_up": "पाई फिर उठ खड़ा हुआ — खोल की एक परत के साथ",
  "sealed": "सील हो गया!",
  "sealed_line": "Vines अब आपकी शेल्फ़ पर है · {n}/38। {s} से. · मीनार ने {t} गिराए, आपने {h}।",
  "torch_out": "मशाल बुझ गई",
  "out_of_hearts": "दिल ख़त्म",
  "lost_line": "{s} से. · {e} ज़मीन तक पहुँच गए। {guest}",
  "try_again": "फिर कोशिश करें",
  "your_house": "आपका घर",
  "move_left": "बाएँ चलें",
  "move_right": "दाएँ चलें",
  "jump": "कूदें",
  "keys_line": "← → / A D  चलें · Space ↑ W  कूदें · गिरे हुए पाई को छुएँ · Esc  रोकें",
  "house_lede": "आप जिस भी पाई को घर लाते हैं, वह शेल्फ़ पर सजता है। फ़र्श पर घूमने वाले Spriteer में बनाए गए हैं।",
  "py_counts": "पाई {a}/{b} · पालतू {c}/{d} · मछलियाँ {e}/{f}",
  "from_sp": "Spriteer से {n}",
  "none_from_sp": "Spriteer से अभी कोई नहीं",
  "door_py": "जब तक कोई रहने न आए, फ़र्श खाली रहता है। spriteer.com पर चार बिंदु रंगिए — आपका घर आपके साथ चलता है।",
  "visit": "देखें",
  "all_nights": "ऐप में सभी 38 रातें खेलिए",
  "privacy": "गोपनीयता"
 },
 "id": {
  "page_title": "Pythoneer — Satu Malam",
  "get_app": "Unduh aplikasinya",
  "h1": "Satu malam. Malam 4.",
  "rules_html": "Sebuah Py mendarat dan mendirikan menara. Kawanan turun dari kedua sisi. <b>Jangan biarkan satu pun sampai ke obor.</b> Injak mereka, atau biarkan dua teman Anda di menara menembak dan mengurung mereka dalam gelembung. Saat Py keluar, pecahkan cangkangnya dua kali, lalu sentuh dia.",
  "night_name": "Malam 4 · Vine Gauntlet",
  "lose_rule": "Anda kalah jika ada yang sampai ke obor, atau ketiga hati Anda habis.",
  "guest_soon": "Setelah kalah {n} kali, seorang tamu bergabung di menara.",
  "guest_count": "Kalah {k} dari {n} — setelah kalah {n} kali, seorang tamu bergabung di menara.",
  "guest_here": "Malam ini seorang Penembak tamu (kekuatan 200) menemani Anda di lantai pertama.",
  "start": "Mulai malam ini",
  "swarm": "Kawanan {n}",
  "py_in": "Py: keluar dalam {n}",
  "py_shell": "Py: cangkang {n}",
  "py_down": "Py: tumbang {n} dtk",
  "say_out": "Py keluar — pecahkan cangkangnya",
  "say_broke": "Cangkangnya pecah — pukul sekali lagi",
  "say_touch": "Sentuh Py untuk menyegelnya",
  "say_up": "Py bangkit lagi — dengan satu lapis cangkang",
  "sealed": "Tersegel!",
  "sealed_line": "Vines kini ada di rak Anda · {n}/38. {s} dtk · menara mengalahkan {t}, Anda {h}.",
  "torch_out": "Obornya padam",
  "out_of_hearts": "Hati habis",
  "lost_line": "{s} dtk · {e} sampai ke tanah. {guest}",
  "try_again": "Coba lagi",
  "your_house": "Rumah Anda",
  "move_left": "Gerak ke kiri",
  "move_right": "Gerak ke kanan",
  "jump": "LOMPAT",
  "keys_line": "← → / A D  Gerak · Space ↑ W  Lompat · Ketuk Py yang tumbang · Esc  Jeda",
  "house_lede": "Setiap Py yang Anda bawa pulang berdiri di rak. Yang berkeliaran di lantai digambar di Spriteer.",
  "py_counts": "Py {a}/{b} · Peliharaan {c}/{d} · Ikan {e}/{f}",
  "from_sp": "{n} dari Spriteer",
  "none_from_sp": "Belum ada dari Spriteer",
  "door_py": "Lantainya kosong sampai ada yang pindah ke sini. Warnai empat titik di spriteer.com — rumah Anda ikut bersama Anda.",
  "visit": "Kunjungi",
  "all_nights": "Mainkan semua 38 malam di aplikasi",
  "privacy": "Privasi"
 },
 "it": {
  "page_title": "Pythoneer — Una notte",
  "get_app": "Scarica l'app",
  "h1": "Una notte. Notte 4.",
  "rules_html": "Un Py atterra e tira su una torre. Lo sciame scende da entrambi i lati. <b>Non farne arrivare nemmeno uno alla torcia.</b> Saltagli in testa, oppure lascia che i tuoi due amici sulla torre li colpiscano e li chiudano in una bolla. Quando il Py esce, rompigli il guscio due volte, poi toccalo.",
  "night_name": "Notte 4 · Vine Gauntlet",
  "lose_rule": "Perdi se qualcosa arriva alla torcia o se esaurisci i tre cuori.",
  "guest_soon": "Dopo {n} sconfitte arriva un ospite sulla torre.",
  "guest_count": "{k} sconfitte su {n} — dopo {n} sconfitte arriva un ospite sulla torre.",
  "guest_here": "Stanotte un Tiratore ospite (potenza 200) ti dà una mano al primo piano.",
  "start": "Inizia la notte",
  "swarm": "Sciame {n}",
  "py_in": "Py: esce tra {n}",
  "py_shell": "Py: guscio {n}",
  "py_down": "Py: a terra {n} s",
  "say_out": "Il Py è uscito — rompigli il guscio",
  "say_broke": "Guscio rotto — colpiscilo ancora una volta",
  "say_touch": "Tocca il Py per sigillarlo",
  "say_up": "Il Py si è rialzato — di nuovo con un guscio",
  "sealed": "Sigillato!",
  "sealed_line": "Vines è sul tuo scaffale · {n}/38. {s} s · la torre ne ha presi {t}, tu {h}.",
  "torch_out": "La torcia si è spenta",
  "out_of_hearts": "Cuori finiti",
  "lost_line": "{s} s · arrivati a terra: {e}. {guest}",
  "try_again": "Riprova",
  "your_house": "La tua casa",
  "move_left": "Vai a sinistra",
  "move_right": "Vai a destra",
  "jump": "SALTA",
  "keys_line": "← → / A D  Muoviti · Space ↑ W  Salta · Tocca il Py a terra · Esc  Pausa",
  "house_lede": "Ogni Py che porti a casa trova posto sullo scaffale. Chi passeggia sul pavimento è disegnato in Spriteer.",
  "py_counts": "Py {a}/{b} · Animali {c}/{d} · Pesci {e}/{f}",
  "from_sp": "{n} da Spriteer",
  "none_from_sp": "Ancora nessuno da Spriteer",
  "door_py": "Il pavimento resta vuoto finché qualcuno non si trasferisce. Colora quattro puntini su spriteer.com — la tua casa ti segue ovunque.",
  "visit": "Visita",
  "all_nights": "Gioca tutte e 38 le notti nell'app",
  "privacy": "Privacy"
 },
 "ja": {
  "page_title": "Pythoneer — 一夜かぎり",
  "get_app": "アプリを入手",
  "h1": "一夜かぎり。第4夜。",
  "rules_html": "パイが降り立ち、塔を建てます。群れが左右から下りてきます。<b>松明には一匹も触れさせないこと。</b>踏みつけるか、塔の上の仲間2人に撃たせて泡に閉じこめましょう。パイが出てきたら殻を2回割り、それからタッチします。",
  "night_name": "第4夜 · Vine Gauntlet",
  "lose_rule": "松明に何かが届くか、ハート3つがなくなると負けです。",
  "guest_soon": "{n}回負けると、助っ人が塔に来ます。",
  "guest_count": "{n}回中{k}回負け — {n}回負けると、助っ人が塔に来ます。",
  "guest_here": "今夜は助っ人のシューター（パワー200）が1階に加わります。",
  "start": "夜をはじめる",
  "swarm": "群れ {n}",
  "py_in": "パイ: あと{n}で登場",
  "py_shell": "パイ: 殻 {n}",
  "py_down": "パイ: ダウン {n}秒",
  "say_out": "パイが出た — 殻を割ろう",
  "say_broke": "殻が割れた — あと一撃",
  "say_touch": "パイにタッチして封印しよう",
  "say_up": "パイが起き上がった — 殻が1枚復活",
  "sealed": "封印！",
  "sealed_line": "Vinesが棚に並びました · {n}/38。{s}秒 · 塔が{t}匹、あなたが{h}匹倒しました。",
  "torch_out": "松明が消えた",
  "out_of_hearts": "ハートが尽きた",
  "lost_line": "{s}秒 · {e}匹が地面に着きました。{guest}",
  "try_again": "もう一度",
  "your_house": "わが家",
  "move_left": "左へ移動",
  "move_right": "右へ移動",
  "jump": "ジャンプ",
  "keys_line": "← → / A D  移動 · Space ↑ W  ジャンプ · ダウンしたパイをタップ · Esc  一時停止",
  "house_lede": "連れ帰ったパイは、みんな棚に並びます。床を歩いているのは、Spriteerで描かれた仲間たちです。",
  "py_counts": "パイ {a}/{b} · ペット {c}/{d} · 魚 {e}/{f}",
  "from_sp": "Spriteer生まれ {n}",
  "none_from_sp": "Spriteer生まれはまだいません",
  "door_py": "誰かが引っ越してくるまで、床は空っぽです。spriteer.comで4つのドットを塗りましょう — 家はどこへでもついてきます。",
  "visit": "行ってみる",
  "all_nights": "全38夜はアプリで",
  "privacy": "プライバシー"
 },
 "ko": {
  "page_title": "Pythoneer — 하룻밤",
  "get_app": "앱 받기",
  "h1": "하룻밤. 네 번째 밤.",
  "rules_html": "파이 하나가 내려와 탑을 세웁니다. 양쪽에서 떼가 몰려 내려옵니다. <b>단 한 마리도 횃불에 닿게 하지 마세요.</b> 직접 밟거나, 탑 위의 두 친구가 쏘아서 거품에 가두게 하세요. 파이가 나오면 껍질을 두 번 깬 뒤 터치하세요.",
  "night_name": "네 번째 밤 · Vine Gauntlet",
  "lose_rule": "무엇이든 횃불에 닿거나 하트 세 개를 모두 잃으면 패배합니다.",
  "guest_soon": "{n}번 지면 게스트가 탑에 합류합니다.",
  "guest_count": "{n}번 중 {k}번 패배 — {n}번 지면 게스트가 탑에 합류합니다.",
  "guest_here": "오늘 밤은 게스트 슈터(파워 200)가 1층에서 함께합니다.",
  "start": "밤 시작",
  "swarm": "떼 {n}",
  "py_in": "파이: {n} 후 등장",
  "py_shell": "파이: 껍질 {n}",
  "py_down": "파이: 기절 {n}초",
  "say_out": "파이 등장 — 껍질을 깨세요",
  "say_broke": "껍질이 깨졌습니다 — 한 번 더 치세요",
  "say_touch": "파이를 터치해 봉인하세요",
  "say_up": "파이가 다시 일어섰습니다 — 껍질 한 겹",
  "sealed": "봉인 완료!",
  "sealed_line": "Vines가 선반에 올랐습니다 · {n}/38. {s}초 · 탑이 {t}마리, 직접 {h}마리 처치.",
  "torch_out": "횃불이 꺼졌습니다",
  "out_of_hearts": "하트를 모두 잃었습니다",
  "lost_line": "{s}초 · {e}마리가 땅에 닿았습니다. {guest}",
  "try_again": "다시 도전",
  "your_house": "내 집",
  "move_left": "왼쪽으로 이동",
  "move_right": "오른쪽으로 이동",
  "jump": "점프",
  "keys_line": "← → / A D  이동 · Space ↑ W  점프 · 쓰러진 파이 탭 · Esc  일시정지",
  "house_lede": "데려온 파이는 모두 선반에 섭니다. 바닥을 걸어 다니는 건 Spriteer에서 그린 친구들입니다.",
  "py_counts": "파이 {a}/{b} · 펫 {c}/{d} · 물고기 {e}/{f}",
  "from_sp": "Spriteer 출신 {n}",
  "none_from_sp": "아직 Spriteer 출신이 없습니다",
  "door_py": "누군가 이사 오기 전까지 바닥은 비어 있습니다. spriteer.com에서 점 네 개를 칠해 보세요 — 내 집은 어디든 따라옵니다.",
  "visit": "가 보기",
  "all_nights": "38개의 밤 모두 앱에서 즐기세요",
  "privacy": "개인정보 처리방침"
 },
 "nl": {
  "page_title": "Pythoneer — Eén nacht",
  "get_app": "Download de app",
  "h1": "Eén nacht. Nacht 4.",
  "rules_html": "Een Py landt en zet een toren neer. Van twee kanten komt de zwerm naar beneden. <b>Laat er niet één bij de fakkel komen.</b> Spring erop, of laat je twee vrienden op de toren ze beschieten en in bellen vangen. Komt de Py tevoorschijn? Kraak dan twee keer zijn pantser en raak hem aan.",
  "night_name": "Nacht 4 · Vine Gauntlet",
  "lose_rule": "Je verliest als er iets bij de fakkel komt of als je drie hartjes op zijn.",
  "guest_soon": "Verlies je {n} keer, dan komt er een gast op de toren.",
  "guest_count": "{k} van {n} keer verloren — verlies je {n} keer, dan komt er een gast op de toren.",
  "guest_here": "Vannacht staat er een gast-Schutter (kracht 200) naast je op de eerste verdieping.",
  "start": "Start de nacht",
  "swarm": "Zwerm {n}",
  "py_in": "Py: verschijnt over {n}",
  "py_shell": "Py: pantser {n}",
  "py_down": "Py: gevloerd {n} s",
  "say_out": "De Py is eruit — kraak zijn pantser",
  "say_broke": "Pantser gebroken — nog één klap",
  "say_touch": "Raak de Py aan om hem te verzegelen",
  "say_up": "De Py staat weer op — met één laag pantser",
  "sealed": "Verzegeld!",
  "sealed_line": "Vines staat op je plank · {n}/38. {s} s · de toren pakte er {t}, jij {h}.",
  "torch_out": "De fakkel is uit",
  "out_of_hearts": "Geen hartjes meer",
  "lost_line": "{s} s · {e} bereikten de grond. {guest}",
  "try_again": "Nog een keer",
  "your_house": "Jouw huis",
  "move_left": "Naar links",
  "move_right": "Naar rechts",
  "jump": "SPRING",
  "keys_line": "← → / A D  Lopen · Space ↑ W  Springen · Tik op de gevloerde Py · Esc  Pauze",
  "house_lede": "Elke Py die je mee naar huis neemt, krijgt een plekje op de plank. Wie over de vloer loopt, is getekend in Spriteer.",
  "py_counts": "Py's {a}/{b} · Huisdieren {c}/{d} · Vissen {e}/{f}",
  "from_sp": "{n} uit Spriteer",
  "none_from_sp": "Nog niemand uit Spriteer",
  "door_py": "De vloer blijft leeg tot er iemand intrekt. Kleur vier puntjes op spriteer.com — je huis gaat met je mee.",
  "visit": "Ga kijken",
  "all_nights": "Speel alle 38 nachten in de app",
  "privacy": "Privacy"
 },
 "pt-BR": {
  "page_title": "Pythoneer — Uma noite",
  "get_app": "Baixe o app",
  "h1": "Uma noite. Noite 4.",
  "rules_html": "Um Py pousa e levanta uma torre. O enxame desce pelos dois lados. <b>Não deixe nenhum chegar à tocha.</b> Pule em cima deles ou deixe seus dois amigos na torre atirarem e prendê-los em bolhas. Quando o Py sair, quebre a carapaça dele duas vezes e depois toque nele.",
  "night_name": "Noite 4 · Vine Gauntlet",
  "lose_rule": "Você perde se algo chegar à tocha ou se seus três corações acabarem.",
  "guest_soon": "Depois de {n} derrotas, um convidado entra na torre.",
  "guest_count": "{k} de {n} derrotas — depois de {n} derrotas, um convidado entra na torre.",
  "guest_here": "Esta noite, um Atirador convidado (poder 200) joga com você no primeiro andar.",
  "start": "Começar a noite",
  "swarm": "Enxame {n}",
  "py_in": "Py: sai em {n}",
  "py_shell": "Py: carapaça {n}",
  "py_down": "Py: caído {n} s",
  "say_out": "O Py saiu — quebre a carapaça",
  "say_broke": "A carapaça quebrou — mais um golpe",
  "say_touch": "Toque no Py para selá-lo",
  "say_up": "O Py se levantou — com uma camada de carapaça",
  "sealed": "Selado!",
  "sealed_line": "Vines está na sua estante · {n}/38. {s} s · a torre pegou {t}, você pegou {h}.",
  "torch_out": "A tocha apagou",
  "out_of_hearts": "Acabaram os corações",
  "lost_line": "{s} s · {e} chegaram ao chão. {guest}",
  "try_again": "Tentar de novo",
  "your_house": "Sua casa",
  "move_left": "Ir para a esquerda",
  "move_right": "Ir para a direita",
  "jump": "PULAR",
  "keys_line": "← → / A D  Mover · Space ↑ W  Pular · Toque no Py caído · Esc  Pausar",
  "house_lede": "Todo Py que você traz para casa fica na estante. Quem anda pelo chão foi desenhado no Spriteer.",
  "py_counts": "Pys {a}/{b} · Bichos {c}/{d} · Peixes {e}/{f}",
  "from_sp": "{n} do Spriteer",
  "none_from_sp": "Ninguém do Spriteer ainda",
  "door_py": "O chão fica vazio até alguém se mudar para cá. Pinte quatro pontinhos em spriteer.com — sua casa vai junto com você.",
  "visit": "Visitar",
  "all_nights": "Jogue as 38 noites no app",
  "privacy": "Privacidade"
 },
 "ru": {
  "page_title": "Pythoneer — Одна ночь",
  "get_app": "Скачать приложение",
  "h1": "Одна ночь. Четвёртая.",
  "rules_html": "Пай приземляется и возводит башню. Рой спускается с обеих сторон. <b>Не подпустите к факелу ни одного.</b> Прыгайте им на головы или дайте двум друзьям на башне подстрелить их и поймать в пузыри. Когда появится Пай, дважды расколите его панцирь, а потом коснитесь его.",
  "night_name": "Ночь 4 · Vine Gauntlet",
  "lose_rule": "Вы проиграете, если кто-то доберётся до факела или закончатся все три сердца.",
  "guest_soon": "После {n} поражений на башню придёт гость.",
  "guest_count": "Поражений: {k} из {n} — после {n} поражений на башню придёт гость.",
  "guest_here": "Этой ночью на первом этаже вам поможет Стрелок-гость (сила 200).",
  "start": "Начать ночь",
  "swarm": "Рой {n}",
  "py_in": "Пай: появится через {n}",
  "py_shell": "Пай: панцирь {n}",
  "py_down": "Пай: в нокауте {n} с",
  "say_out": "Пай появился — расколите панцирь",
  "say_broke": "Панцирь треснул — ещё один удар",
  "say_touch": "Коснитесь Пая, чтобы запечатать",
  "say_up": "Пай снова на ногах — один слой панциря",
  "sealed": "Запечатан!",
  "sealed_line": "Vines на вашей полке · {n}/38. {s} с · башня взяла {t}, вы — {h}.",
  "torch_out": "Факел погас",
  "out_of_hearts": "Сердца закончились",
  "lost_line": "{s} с · до земли добрались: {e}. {guest}",
  "try_again": "Ещё раз",
  "your_house": "Ваш дом",
  "move_left": "Влево",
  "move_right": "Вправо",
  "jump": "ПРЫЖОК",
  "keys_line": "← → / A D  Ходьба · Space ↑ W  Прыжок · Коснитесь Пая в нокауте · Esc  Пауза",
  "house_lede": "Каждый Пай, которого вы приведёте домой, встаёт на полку. А тех, кто ходит по полу, рисуют в Spriteer.",
  "py_counts": "Паи {a}/{b} · Питомцы {c}/{d} · Рыбы {e}/{f}",
  "from_sp": "Из Spriteer: {n}",
  "none_from_sp": "Из Spriteer пока никого",
  "door_py": "Пол пустует, пока кто-нибудь не въедет. Закрасьте четыре точки на spriteer.com — ваш дом всегда с вами.",
  "visit": "Заглянуть",
  "all_nights": "Все 38 ночей — в приложении",
  "privacy": "Конфиденциальность"
 },
 "sv": {
  "page_title": "Pythoneer — En natt",
  "get_app": "Hämta appen",
  "h1": "En natt. Natt 4.",
  "rules_html": "En Py landar och bygger ett torn. Svärmen väller ner från båda hållen. <b>Låt ingen av dem nå facklan.</b> Hoppa på dem, eller låt dina två vänner i tornet skjuta och fånga dem i bubblor. När Py kommer ut knäcker du skalet två gånger och rör sedan vid den.",
  "night_name": "Natt 4 · Vine Gauntlet",
  "lose_rule": "Du förlorar om något når facklan eller om dina tre hjärtan tar slut.",
  "guest_soon": "Efter {n} förluster får tornet en gäst.",
  "guest_count": "Förlorat {k} av {n} — efter {n} förluster får tornet en gäst.",
  "guest_here": "I natt får du hjälp av en gästskytt (kraft 200) på första våningen.",
  "start": "Starta natten",
  "swarm": "Svärm {n}",
  "py_in": "Py: kommer ut om {n}",
  "py_shell": "Py: skal {n}",
  "py_down": "Py: nere {n} s",
  "say_out": "Py är ute — knäck skalet",
  "say_broke": "Skalet sprack — ett slag till",
  "say_touch": "Rör vid Py för att försegla den",
  "say_up": "Py är uppe igen — ett lager skal",
  "sealed": "Förseglad!",
  "sealed_line": "Vines står på din hylla · {n}/38. {s} s · tornet fällde {t}, du fällde {h}.",
  "torch_out": "Facklan slocknade",
  "out_of_hearts": "Slut på hjärtan",
  "lost_line": "{s} s · {e} nådde marken. {guest}",
  "try_again": "Försök igen",
  "your_house": "Ditt hus",
  "move_left": "Gå åt vänster",
  "move_right": "Gå åt höger",
  "jump": "HOPPA",
  "keys_line": "← → / A D  Gå · Space ↑ W  Hoppa · Tryck på Py när den är nere · Esc  Paus",
  "house_lede": "Varje Py du tar hem står på hyllan. De som går omkring på golvet är ritade i Spriteer.",
  "py_counts": "Py {a}/{b} · Husdjur {c}/{d} · Fiskar {e}/{f}",
  "from_sp": "{n} från Spriteer",
  "none_from_sp": "Ingen från Spriteer än",
  "door_py": "Golvet står tomt tills någon flyttar in. Fyll i fyra prickar på spriteer.com — ditt hus följer med dig.",
  "visit": "Besök",
  "all_nights": "Spela alla 38 nätter i appen",
  "privacy": "Integritet"
 },
 "th": {
  "page_title": "Pythoneer — หนึ่งคืน",
  "get_app": "ดาวน์โหลดแอป",
  "h1": "หนึ่งคืน คืนที่ 4",
  "rules_html": "ไพตัวหนึ่งร่อนลงมาแล้วสร้างหอคอยขึ้น ฝูงศัตรูบุกลงมาทั้งสองฝั่ง <b>อย่าให้ตัวไหนไปถึงคบเพลิงได้</b> กระโดดเหยียบพวกมัน หรือให้เพื่อนสองคนบนหอคอยยิงแล้วขังไว้ในฟอง พอไพออกมา ทุบเปลือกมันสองครั้ง แล้วแตะตัวมัน",
  "night_name": "คืนที่ 4 · Vine Gauntlet",
  "lose_rule": "แพ้ถ้ามีอะไรไปถึงคบเพลิง หรือหัวใจทั้งสามดวงหมด",
  "guest_soon": "แพ้ครบ {n} ครั้ง จะมีแขกขึ้นมาช่วยบนหอคอย",
  "guest_count": "แพ้แล้ว {k} จาก {n} ครั้ง — แพ้ครบ {n} ครั้ง จะมีแขกขึ้นมาช่วยบนหอคอย",
  "guest_here": "คืนนี้มีนักยิงรับเชิญ (พลัง 200) มาช่วยคุณที่ชั้นหนึ่ง",
  "start": "เริ่มคืนนี้",
  "swarm": "ฝูง {n}",
  "py_in": "ไพ: ออกมาใน {n}",
  "py_shell": "ไพ: เปลือก {n}",
  "py_down": "ไพ: ล้มอยู่ {n} วิ",
  "say_out": "ไพออกมาแล้ว — ทุบเปลือกเลย",
  "say_broke": "เปลือกแตกแล้ว — ตีอีกที",
  "say_touch": "แตะไพเพื่อผนึก",
  "say_up": "ไพลุกขึ้นมาอีกแล้ว — กลับมามีเปลือกหนึ่งชั้น",
  "sealed": "ผนึกแล้ว!",
  "sealed_line": "Vines ขึ้นชั้นวางของคุณแล้ว · {n}/38 {s} วิ · หอคอยจัดการ {t} คุณจัดการ {h}",
  "torch_out": "คบเพลิงดับแล้ว",
  "out_of_hearts": "หัวใจหมดแล้ว",
  "lost_line": "{s} วิ · หลุดถึงพื้น {e} ตัว {guest}",
  "try_again": "ลองอีกครั้ง",
  "your_house": "บ้านของคุณ",
  "move_left": "ไปทางซ้าย",
  "move_right": "ไปทางขวา",
  "jump": "กระโดด",
  "keys_line": "← → / A D  เดิน · Space ↑ W  กระโดด · แตะไพที่ล้มอยู่ · Esc  พัก",
  "house_lede": "ไพทุกตัวที่คุณพากลับบ้านจะยืนเรียงบนชั้นวาง ส่วนตัวที่เดินไปมาบนพื้นวาดขึ้นใน Spriteer",
  "py_counts": "ไพ {a}/{b} · สัตว์เลี้ยง {c}/{d} · ปลา {e}/{f}",
  "from_sp": "จาก Spriteer {n} ตัว",
  "none_from_sp": "ยังไม่มีใครมาจาก Spriteer",
  "door_py": "พื้นจะว่างอยู่จนกว่าจะมีใครย้ายเข้ามา ไปเติมสี่จุดที่ spriteer.com — บ้านของคุณจะไปกับคุณด้วย",
  "visit": "แวะไปดู",
  "all_nights": "เล่นครบ 38 คืนในแอป",
  "privacy": "ความเป็นส่วนตัว"
 },
 "tr": {
  "page_title": "Pythoneer — Bir Gece",
  "get_app": "Uygulamayı indir",
  "h1": "Bir gece. 4. gece.",
  "rules_html": "Bir Py iner ve bir kule kurar. Sürü iki yandan aşağı akın eder. <b>Hiçbirini meşaleye ulaştırma.</b> Üstlerine zıpla ya da kuledeki iki arkadaşın ateş edip onları baloncuğa hapsetsin. Py ortaya çıkınca kabuğunu iki kez kır, sonra ona dokun.",
  "night_name": "4. gece · Vine Gauntlet",
  "lose_rule": "Meşaleye bir şey ulaşırsa ya da üç kalbin biterse kaybedersin.",
  "guest_soon": "{n} yenilgiden sonra kuleye bir misafir gelir.",
  "guest_count": "{k}/{n} yenilgi — {n} yenilgiden sonra kuleye bir misafir gelir.",
  "guest_here": "Bu gece birinci katta yanında misafir bir Nişancı (güç 200) var.",
  "start": "Geceyi başlat",
  "swarm": "Sürü {n}",
  "py_in": "Py: çıkmasına {n}",
  "py_shell": "Py: kabuk {n}",
  "py_down": "Py: yerde {n} sn",
  "say_out": "Py çıktı — kabuğunu kır",
  "say_broke": "Kabuk kırıldı — bir kez daha vur",
  "say_touch": "Mühürlemek için Py'a dokun",
  "say_up": "Py yeniden kalktı — tek kat kabuk",
  "sealed": "Mühürlendi!",
  "sealed_line": "Vines rafında · {n}/38. {s} sn · kule {t}, sen {h} tane indirdin.",
  "torch_out": "Meşale söndü",
  "out_of_hearts": "Kalp kalmadı",
  "lost_line": "{s} sn · {e} tanesi yere ulaştı. {guest}",
  "try_again": "Tekrar dene",
  "your_house": "Evin",
  "move_left": "Sola git",
  "move_right": "Sağa git",
  "jump": "ZIPLA",
  "keys_line": "← → / A D  Yürü · Space ↑ W  Zıpla · Yerdeki Py'a dokun · Esc  Duraklat",
  "house_lede": "Eve getirdiğin her Py rafta durur. Zeminde dolaşanlar Spriteer'da çizilir.",
  "py_counts": "Py {a}/{b} · Evcil {c}/{d} · Balık {e}/{f}",
  "from_sp": "Spriteer'dan {n}",
  "none_from_sp": "Henüz Spriteer'dan kimse yok",
  "door_py": "Biri taşınana kadar zemin boş kalır. spriteer.com'da dört nokta doldur — evin de seninle gelir.",
  "visit": "Ziyaret et",
  "all_nights": "38 gecenin hepsini uygulamada oyna",
  "privacy": "Gizlilik"
 },
 "vi": {
  "page_title": "Pythoneer — Một đêm",
  "get_app": "Tải ứng dụng",
  "h1": "Một đêm. Đêm 4.",
  "rules_html": "Một Py đáp xuống và dựng lên một tòa tháp. Bầy quái tràn xuống từ hai phía. <b>Đừng để con nào chạm tới ngọn đuốc.</b> Nhảy lên đầu chúng, hoặc để hai người bạn trên tháp bắn và nhốt chúng vào bong bóng. Khi Py chui ra, đập vỡ vỏ nó hai lần rồi chạm vào nó.",
  "night_name": "Đêm 4 · Vine Gauntlet",
  "lose_rule": "Thua nếu có thứ gì chạm tới ngọn đuốc, hoặc bạn hết ba trái tim.",
  "guest_soon": "Thua {n} lần, sẽ có một vị khách lên tháp giúp bạn.",
  "guest_count": "Đã thua {k}/{n} — thua {n} lần, sẽ có một vị khách lên tháp giúp bạn.",
  "guest_here": "Đêm nay có một Xạ thủ khách mời (sức mạnh 200) sát cánh cùng bạn ở tầng một.",
  "start": "Bắt đầu đêm nay",
  "swarm": "Bầy {n}",
  "py_in": "Py: ra sau {n}",
  "py_shell": "Py: vỏ {n}",
  "py_down": "Py: gục {n} giây",
  "say_out": "Py ra rồi — đập vỡ vỏ đi",
  "say_broke": "Vỡ vỏ rồi — đánh thêm một cái",
  "say_touch": "Chạm vào Py để phong ấn",
  "say_up": "Py đứng dậy rồi — giờ có một lớp vỏ",
  "sealed": "Đã phong ấn!",
  "sealed_line": "Vines đã lên kệ của bạn · {n}/38. {s} giây · tháp hạ {t}, bạn hạ {h}.",
  "torch_out": "Ngọn đuốc đã tắt",
  "out_of_hearts": "Hết tim",
  "lost_line": "{s} giây · {e} con chạm đất. {guest}",
  "try_again": "Thử lại",
  "your_house": "Nhà của bạn",
  "move_left": "Sang trái",
  "move_right": "Sang phải",
  "jump": "NHẢY",
  "keys_line": "← → / A D  Di chuyển · Space ↑ W  Nhảy · Chạm vào Py đang gục · Esc  Tạm dừng",
  "house_lede": "Mỗi Py bạn mang về nhà đều đứng trên kệ. Những nhân vật đi lại trên sàn được vẽ bằng Spriteer.",
  "py_counts": "Py {a}/{b} · Thú cưng {c}/{d} · Cá {e}/{f}",
  "from_sp": "{n} từ Spriteer",
  "none_from_sp": "Chưa có ai từ Spriteer",
  "door_py": "Sàn nhà còn trống cho đến khi có ai dọn vào. Tô bốn chấm ở spriteer.com — nhà của bạn sẽ đi cùng bạn.",
  "visit": "Ghé thăm",
  "all_nights": "Chơi đủ 38 đêm trong ứng dụng",
  "privacy": "Quyền riêng tư"
 },
 "zh-Hans": {
  "page_title": "Pythoneer — 一夜",
  "get_app": "获取 App",
  "h1": "一夜。第 4 夜。",
  "rules_html": "一只派落地，立起一座塔。怪群从两侧涌下。<b>一只也别让它们碰到火炬。</b>踩扁它们，或者让塔上的两个伙伴开火，用泡泡把它们困住。派现身后，把它的壳敲破两次，再碰它一下。",
  "night_name": "第 4 夜 · Vine Gauntlet",
  "lose_rule": "只要有东西碰到火炬，或三颗心全部用完，就输了。",
  "guest_soon": "输满 {n} 次，会有一位客人来塔上助阵。",
  "guest_count": "已输 {k}/{n} 次——输满 {n} 次，会有一位客人来塔上助阵。",
  "guest_here": "今晚有一位客串射手（威力 200）在一楼助你一臂之力。",
  "start": "开始这一夜",
  "swarm": "怪群 {n}",
  "py_in": "派：{n} 后出现",
  "py_shell": "派：壳 {n}",
  "py_down": "派：倒地 {n} 秒",
  "say_out": "派出来了——敲破它的壳",
  "say_broke": "壳破了——再打一下",
  "say_touch": "碰一下派，把它封印",
  "say_up": "派重新站起来了——长出一层壳",
  "sealed": "封印成功！",
  "sealed_line": "Vines 已摆上你的架子 · {n}/38。{s} 秒 · 塔击倒 {t} 只，你踩倒 {h} 只。",
  "torch_out": "火炬熄灭了",
  "out_of_hearts": "心用完了",
  "lost_line": "{s} 秒 · {e} 只落到了地面。{guest}",
  "try_again": "再试一次",
  "your_house": "你的家",
  "move_left": "向左",
  "move_right": "向右",
  "jump": "跳",
  "keys_line": "← → / A D  移动 · Space ↑ W  跳 · 点击倒地的派 · Esc  暂停",
  "house_lede": "你带回家的每只派都会站在架子上。在地上走来走去的，是在 Spriteer 里画出来的。",
  "py_counts": "派 {a}/{b} · 宠物 {c}/{d} · 鱼 {e}/{f}",
  "from_sp": "{n} 位来自 Spriteer",
  "none_from_sp": "还没有来自 Spriteer 的角色",
  "door_py": "有人搬进来之前，地板都空着。去 spriteer.com 填上四个点——你的家会跟着你走。",
  "visit": "去看看",
  "all_nights": "到 App 里玩全部 38 夜",
  "privacy": "隐私政策"
 },
 "zh-Hant": {
  "page_title": "Pythoneer — 一夜",
  "get_app": "取得 App",
  "h1": "一夜。第 4 夜。",
  "rules_html": "一隻派落地，立起一座塔。怪群從兩側湧下。<b>一隻也別讓牠們碰到火炬。</b>踩扁牠們，或者讓塔上的兩個夥伴開火，用泡泡把牠們困住。派現身後，把牠的殼敲破兩次，再碰牠一下。",
  "night_name": "第 4 夜 · Vine Gauntlet",
  "lose_rule": "只要有東西碰到火炬，或三顆心全部用完，就輸了。",
  "guest_soon": "輸滿 {n} 次，會有一位客人來塔上助陣。",
  "guest_count": "已輸 {k}/{n} 次——輸滿 {n} 次，會有一位客人來塔上助陣。",
  "guest_here": "今晚有一位客串射手（威力 200）在一樓助你一臂之力。",
  "start": "開始這一夜",
  "swarm": "怪群 {n}",
  "py_in": "派：{n} 後出現",
  "py_shell": "派：殼 {n}",
  "py_down": "派：倒地 {n} 秒",
  "say_out": "派出來了——敲破牠的殼",
  "say_broke": "殼破了——再打一下",
  "say_touch": "碰一下派，把牠封印",
  "say_up": "派重新站起來了——長出一層殼",
  "sealed": "封印成功！",
  "sealed_line": "Vines 已擺上你的架子 · {n}/38。{s} 秒 · 塔擊倒 {t} 隻，你踩倒 {h} 隻。",
  "torch_out": "火炬熄滅了",
  "out_of_hearts": "心用完了",
  "lost_line": "{s} 秒 · {e} 隻落到了地面。{guest}",
  "try_again": "再試一次",
  "your_house": "你的家",
  "move_left": "向左",
  "move_right": "向右",
  "jump": "跳",
  "keys_line": "← → / A D  移動 · Space ↑ W  跳 · 點一下倒地的派 · Esc  暫停",
  "house_lede": "你帶回家的每隻派都會站在架子上。在地上走來走去的，是在 Spriteer 裡畫出來的。",
  "py_counts": "派 {a}/{b} · 寵物 {c}/{d} · 魚 {e}/{f}",
  "from_sp": "{n} 位來自 Spriteer",
  "none_from_sp": "還沒有來自 Spriteer 的角色",
  "door_py": "有人搬進來之前，地板都空著。去 spriteer.com 填上四個點——你的家會跟著你走。",
  "visit": "去看看",
  "all_nights": "到 App 裡玩全部 38 夜",
  "privacy": "隱私權政策"
 }
};
